<?php
namespace App\Services;

use App\Support\Slug;

final class ProductImportService
{
    public function commit(\PDO$pdo,int$storeId,array$rows):array
    {
        $access=new PlanAccessService;$access->context($storeId,$pdo,true,false);$required=$this->requiredCapacity($pdo,$storeId,$rows);$access->assertCanAddMany($storeId,$required,$pdo);$created=0;$updated=0;$categories=0;$find=$pdo->prepare('SELECT id FROM products WHERE store_id=? AND sku=? AND deleted_at IS NULL FOR UPDATE');$update=$pdo->prepare('UPDATE products SET category_id=?,name=?,description=?,price=?,compare_price=?,availability=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND store_id=?');$insert=$pdo->prepare("INSERT INTO products (store_id,category_id,name,slug,sku,description,price,compare_price,availability,is_featured,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,0,'DRAFT',UTC_TIMESTAMP(),UTC_TIMESTAMP())");
        foreach($rows as$row){$categoryId=null;if($row['category']!==''){$categoryId=$this->category($pdo,$storeId,$row['category'],$categories);}$find->execute([$storeId,$row['sku']]);$id=$find->fetchColumn();$compare=$row['compare_price']===''?null:$row['compare_price'];$description=$row['description']===''?null:$row['description'];if($id){$update->execute([$categoryId,$row['name'],$description,$row['price'],$compare,$row['availability'],$id,$storeId]);$updated++;}else{$slug=$this->uniqueSlug($pdo,$storeId,$row['name']);$insert->execute([$storeId,$categoryId,$row['name'],$slug,$row['sku'],$description,$row['price'],$compare,$row['availability']]);$created++;}}
        return['created'=>$created,'updated'=>$updated,'categories'=>$categories];
    }
    private function requiredCapacity(\PDO$pdo,int$storeId,array$rows):array{$existingProducts=$pdo->prepare('SELECT sku FROM products WHERE store_id=? AND deleted_at IS NULL');$existingProducts->execute([$storeId]);$productSet=[];foreach($existingProducts->fetchAll(\PDO::FETCH_COLUMN)as$sku)$productSet[mb_strtolower((string)$sku)]=true;$existingCategories=$pdo->prepare('SELECT name FROM categories WHERE store_id=? AND deleted_at IS NULL');$existingCategories->execute([$storeId]);$categorySet=[];foreach($existingCategories->fetchAll(\PDO::FETCH_COLUMN)as$name)$categorySet[mb_strtolower(trim((string)$name))]=true;$newProducts=0;$newCategories=0;foreach($rows as$row){$sku=mb_strtolower((string)$row['sku']);if(!isset($productSet[$sku])){$productSet[$sku]=true;$newProducts++;}$category=mb_strtolower(trim((string)$row['category']));if($category!==''&&!isset($categorySet[$category])){$categorySet[$category]=true;$newCategories++;}}return['products'=>$newProducts,'categories'=>$newCategories];}
    private function category(\PDO$pdo,int$storeId,string$name,int&$created):int{$s=$pdo->prepare('SELECT id FROM categories WHERE store_id=? AND name=? AND deleted_at IS NULL LIMIT 1 FOR UPDATE');$s->execute([$storeId,$name]);$id=$s->fetchColumn();if($id)return(int)$id;$slug=$this->uniqueCategorySlug($pdo,$storeId,$name);$i=$pdo->prepare("INSERT INTO categories (store_id,name,slug,description,sort_order,status,created_at,updated_at) SELECT ?,?,?,NULL,COALESCE(MAX(sort_order),-1)+1,'ACTIVE',UTC_TIMESTAMP(),UTC_TIMESTAMP() FROM categories WHERE store_id=? AND deleted_at IS NULL");$i->execute([$storeId,$name,$slug,$storeId]);$created++;return(int)$pdo->lastInsertId();}
    private function uniqueSlug(\PDO$pdo,int$storeId,string$name):string{$base=Slug::make($name)?:'product';$slug=$base;$n=2;$s=$pdo->prepare('SELECT 1 FROM products WHERE store_id=? AND slug=? LIMIT 1');while(true){$s->execute([$storeId,$slug]);if(!$s->fetchColumn())return$slug;$slug=mb_substr($base,0,170).'-'.$n++;}}
    private function uniqueCategorySlug(\PDO$pdo,int$storeId,string$name):string{$base=mb_substr(Slug::make($name)?:'category',0,90);$slug=$base;$n=2;$s=$pdo->prepare('SELECT 1 FROM categories WHERE store_id=? AND slug=? LIMIT 1');while(true){$s->execute([$storeId,$slug]);if(!$s->fetchColumn())return$slug;$slug=mb_substr($base,0,90).'-'.$n++;}}
}
