<?php
namespace App\Services;

use App\Core\Database;
use App\Repositories\{AuditLogRepository,SubscriptionRepository};
use App\Services\Billing\PaymentProviderFactory;
use App\Support\Money;

final class SubscriptionService
{
    public function requestChange(array$store,int$userId,string$targetCode):array
    {
        $repo=new SubscriptionRepository;$target=$repo->planByCode(strtoupper($targetCode));if(!$target)throw new \DomainException('Choose an available plan.');$access=(new PlanAccessService)->context((int)$store['id']);$current=$access['subscription'];if(!$current)throw new \RuntimeException('Subscription is not configured.');$from=$access['plan'];$samePlan=(int)$from['id']===(int)$target['id'];$renewal=$samePlan&&$this->renewalDue($current);if($samePlan&&!$renewal)throw new \DomainException('This store is already on that plan.');$existing=$this->openRequest((int)$current['id']);if($existing){if((int)$existing['to_plan_id']===(int)$target['id'])return['status'=>$existing['status'],'duplicate'=>true];throw new \DomainException('Cancel the current pending plan change before requesting another.');}$downgrade=Money::minor((string)$target['monthly_price'])<Money::minor((string)$from['monthly_price']);$automaticDowngrade=$downgrade&&Money::minor((string)$target['monthly_price'])===0;
        $pdo=Database::connection();$pdo->beginTransaction();try{$lockedAccess=(new PlanAccessService)->context((int)$store['id'],$pdo,true);$locked=$lockedAccess['subscription'];if(!$locked||(int)$lockedAccess['plan']['id']!==(int)$from['id'])throw new \DomainException('The subscription changed. Refresh and try again.');$pending=$pdo->prepare("SELECT id,to_plan_id,status FROM subscription_change_requests WHERE subscription_id=? AND status IN ('PENDING','SCHEDULED') ORDER BY id DESC LIMIT 1 FOR UPDATE");$pending->execute([$locked['id']]);$existing=$pending->fetch();if($existing){if((int)$existing['to_plan_id']===(int)$target['id']){$pdo->commit();return['status'=>$existing['status'],'duplicate'=>true];}throw new \DomainException('Cancel the current pending plan change before requesting another.');}$sequence=$this->nextRequestSequence((int)$locked['id'],$pdo);$idempotencyKey='store-'.$store['id'].'-subscription-'.$locked['id'].'-request-'.$sequence.'-plan-'.$target['id'];$providerResult=$automaticDowngrade?['status'=>'SCHEDULED','reference'=>null,'metadata'=>[]]:PaymentProviderFactory::make()->requestPaidChange($store,$from,$target,$idempotencyKey);
            $effectiveAt=null;$status='PENDING';if($automaticDowngrade){$period=$locked['current_period_ends_at']?strtotime($locked['current_period_ends_at']):false;if($period&&$period>time()){$effectiveAt=gmdate('Y-m-d H:i:s',$period);$status='SCHEDULED';$pdo->prepare('UPDATE subscriptions SET pending_plan_id=?,scheduled_change_at=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND store_id=?')->execute([$target['id'],$effectiveAt,$locked['id'],$store['id']]);}else{$status='APPLIED';$effectiveAt=gmdate('Y-m-d H:i:s');$this->apply($pdo,$locked,$target,'subscription.downgraded');}}
            $type=$samePlan?'CHANGE':($downgrade?'DOWNGRADE':'UPGRADE');$s=$pdo->prepare('INSERT INTO subscription_change_requests (store_id,subscription_id,from_plan_id,to_plan_id,requested_by_user_id,change_type,status,provider,provider_reference,effective_at,applied_at,metadata,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?, ?,UTC_TIMESTAMP(),UTC_TIMESTAMP())');$s->execute([$store['id'],$locked['id'],$from['id'],$target['id'],$userId,$type,$status,config('billing')['provider'],$providerResult['reference'],$effectiveAt,$status==='APPLIED'?$effectiveAt:null,json_encode($providerResult['metadata'],JSON_UNESCAPED_SLASHES)]);$pdo->commit();return['status'=>$status,'duplicate'=>false];
        }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public function cancelRequest(int$storeId,int$userId,int$requestId):void
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare("SELECT r.*,sub.pending_plan_id FROM subscription_change_requests r JOIN subscriptions sub ON sub.id=r.subscription_id AND sub.store_id=r.store_id WHERE r.id=? AND r.store_id=? AND r.requested_by_user_id=? AND r.status IN ('PENDING','SCHEDULED') FOR UPDATE");$s->execute([$requestId,$storeId,$userId]);$request=$s->fetch();if(!$request)throw new \DomainException('That pending change is unavailable.');$pdo->prepare("UPDATE subscription_change_requests SET status='CANCELLED',cancelled_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=? AND store_id=?")->execute([$requestId,$storeId]);if((int)$request['pending_plan_id']===(int)$request['to_plan_id'])$pdo->prepare('UPDATE subscriptions SET pending_plan_id=NULL,scheduled_change_at=NULL,updated_at=UTC_TIMESTAMP() WHERE id=? AND store_id=?')->execute([$request['subscription_id'],$storeId]);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public function activate(int$storeId,string$planCode,int$periodDays,?string$providerReference=null,?int$actorId=null):void
    {
        $repo=new SubscriptionRepository;$pdo=Database::connection();$pdo->beginTransaction();try{$sub=$repo->current($storeId,$pdo,true);if(!$sub)throw new \DomainException('Subscription not found.');$plan=$repo->planByCode(strtoupper($planCode),false,$pdo);if(!$plan)throw new \DomainException('Plan not found.');$fromPlan=(int)$sub['plan_id'];$ends=Money::minor((string)$plan['monthly_price'])===0?null:gmdate('Y-m-d H:i:s',time()+max(1,$periodDays)*86400);$pdo->prepare("UPDATE subscriptions SET plan_id=?,pending_plan_id=NULL,status='ACTIVE',provider=?,provider_subscription_ref=COALESCE(?,provider_subscription_ref),started_at=UTC_TIMESTAMP(),trial_ends_at=NULL,current_period_ends_at=?,grace_ends_at=NULL,scheduled_change_at=NULL,cancelled_at=NULL,ended_at=NULL,updated_at=UTC_TIMESTAMP() WHERE id=? AND store_id=?")->execute([$plan['id'],config('billing')['provider'],$providerReference,$ends,$sub['id'],$storeId]);$pdo->prepare("UPDATE subscription_change_requests SET status='APPLIED',effective_at=UTC_TIMESTAMP(),applied_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE subscription_id=? AND to_plan_id=? AND status='PENDING'")->execute([$sub['id'],$plan['id']]);$this->event($pdo,$storeId,(int)$sub['id'],'subscription.activated',$sub['status'],'ACTIVE',$fromPlan,(int)$plan['id'],['period_days'=>$periodDays,'actor_user_id'=>$actorId]);if($actorId)(new AuditLogRepository)->record($actorId,'admin.subscription_plan_changed','store',$storeId,['from_plan'=>$sub['plan_code'],'to_plan'=>$plan['code'],'period_days'=>Money::minor((string)$plan['monthly_price'])===0?null:$periodDays]);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public function processLifecycle():array
    {
        $pdo=Database::connection();$rows=$pdo->query("SELECT store_id FROM subscriptions WHERE (pending_plan_id IS NOT NULL AND scheduled_change_at<=UTC_TIMESTAMP()) OR (status='TRIAL' AND trial_ends_at IS NOT NULL AND trial_ends_at<=UTC_TIMESTAMP()) OR (status='ACTIVE' AND current_period_ends_at IS NOT NULL AND current_period_ends_at<=UTC_TIMESTAMP()) OR (status IN ('PAST_DUE','GRACE') AND grace_ends_at IS NOT NULL AND grace_ends_at<=UTC_TIMESTAMP()) ORDER BY id")->fetchAll(\PDO::FETCH_COLUMN);$result=['changed'=>0,'errors'=>0];foreach($rows as$storeId){try{$this->processStore((int)$storeId);$result['changed']++;}catch(\Throwable$e){$result['errors']++;\App\Support\Logger::error('Subscription lifecycle processing failed',$e);}}return$result;
    }

    private function processStore(int$storeId):void
    {
        $repo=new SubscriptionRepository;$pdo=Database::connection();$pdo->beginTransaction();try{$sub=$repo->current($storeId,$pdo,true);if(!$sub){$pdo->rollBack();return;}$now=time();if($sub['pending_plan_id']&&$sub['scheduled_change_at']&&strtotime($sub['scheduled_change_at'])<=$now){$target=$pdo->prepare('SELECT * FROM plans WHERE id=? AND is_active=1');$target->execute([$sub['pending_plan_id']]);$plan=$target->fetch();if(!$plan)throw new \RuntimeException('Scheduled plan is unavailable.');$this->decode($plan);$this->apply($pdo,$sub,$plan,'subscription.scheduled_change_applied');$pdo->prepare("UPDATE subscription_change_requests SET status='APPLIED',applied_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE subscription_id=? AND to_plan_id=? AND status='SCHEDULED'")->execute([$sub['id'],$plan['id']]);}
            elseif($sub['status']==='TRIAL'&&$sub['trial_ends_at']&&strtotime($sub['trial_ends_at'])<=$now){$grace=$this->graceDate();$pdo->prepare("UPDATE subscriptions SET status='GRACE',grace_ends_at=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$grace,$sub['id']]);$this->event($pdo,$storeId,(int)$sub['id'],'subscription.trial_ended','TRIAL','GRACE',(int)$sub['plan_id'],(int)$sub['plan_id']);}
            elseif($sub['status']==='ACTIVE'&&$sub['current_period_ends_at']&&strtotime($sub['current_period_ends_at'])<=$now){$grace=$this->graceDate();$pdo->prepare("UPDATE subscriptions SET status='PAST_DUE',grace_ends_at=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$grace,$sub['id']]);$this->event($pdo,$storeId,(int)$sub['id'],'subscription.period_ended','ACTIVE','PAST_DUE',(int)$sub['plan_id'],(int)$sub['plan_id']);}
            elseif(in_array($sub['status'],['PAST_DUE','GRACE'],true)&&$sub['grace_ends_at']&&strtotime($sub['grace_ends_at'])<=$now){$pdo->prepare("UPDATE subscriptions SET status='EXPIRED',ended_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$sub['id']]);$this->event($pdo,$storeId,(int)$sub['id'],'subscription.expired',$sub['status'],'EXPIRED',(int)$sub['plan_id'],(int)$sub['plan_id']);}$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    private function apply(\PDO$pdo,array$sub,array$plan,string$event):void{$pdo->prepare("UPDATE subscriptions SET plan_id=?,pending_plan_id=NULL,status='ACTIVE',current_period_ends_at=NULL,grace_ends_at=NULL,scheduled_change_at=NULL,cancelled_at=NULL,ended_at=NULL,updated_at=UTC_TIMESTAMP() WHERE id=? AND store_id=?")->execute([$plan['id'],$sub['id'],$sub['store_id']]);$this->event($pdo,(int)$sub['store_id'],(int)$sub['id'],$event,$sub['status'],'ACTIVE',(int)$sub['plan_id'],(int)$plan['id']);}
    private function event(\PDO$pdo,int$storeId,int$subscriptionId,string$type,?string$fromStatus,?string$toStatus,?int$fromPlan=null,?int$toPlan=null,array$metadata=[]):void{$s=$pdo->prepare('INSERT INTO subscription_events (store_id,subscription_id,event_type,from_status,to_status,from_plan_id,to_plan_id,metadata,created_at) VALUES (?,?,?,?,?,?,?,?,UTC_TIMESTAMP())');$s->execute([$storeId,$subscriptionId,$type,$fromStatus,$toStatus,$fromPlan,$toPlan,json_encode($metadata,JSON_UNESCAPED_SLASHES)]);}
    private function openRequest(int$subscriptionId):?array{$s=Database::connection()->prepare("SELECT id,to_plan_id,status FROM subscription_change_requests WHERE subscription_id=? AND status IN ('PENDING','SCHEDULED') ORDER BY id DESC LIMIT 1");$s->execute([$subscriptionId]);return$s->fetch()?:null;}
    private function nextRequestSequence(int$subscriptionId,\PDO$pdo):int{$s=$pdo->prepare('SELECT COALESCE(MAX(id),0)+1 FROM subscription_change_requests WHERE subscription_id=?');$s->execute([$subscriptionId]);return max(1,(int)$s->fetchColumn());}
    private function renewalDue(array$subscription):bool{$now=time();if(in_array($subscription['status'],['PAST_DUE','GRACE','EXPIRED'],true))return true;if($subscription['status']==='ACTIVE'&&$subscription['current_period_ends_at'])return strtotime($subscription['current_period_ends_at'])<=$now;if($subscription['status']==='TRIAL'&&$subscription['trial_ends_at'])return strtotime($subscription['trial_ends_at'])<=$now;return false;}
    private function graceDate():string{return gmdate('Y-m-d H:i:s',time()+config('billing')['grace_days']*86400);}
    private function decode(array&$plan):void{$features=json_decode((string)$plan['features'],true);$limits=json_decode((string)$plan['limits'],true);$plan['features']=is_array($features)?$features:[];$plan['limits']=is_array($limits)?$limits:[];}
}
