<?php $editing=(bool)$offer;$old=App\Core\Session::get('_old',[]);$value=static fn($key,$default='')=>$old[$key]??($offer[$key]??$default);$toLocal=static fn(?string$v):string=>$v?gmdate('Y-m-d\TH:i',strtotime($v)):'';$bundleItems=$offer['items']??[]; ?>
<section class="page-head"><div><a class="back-link" href="/merchant/offers">← Bundles & offers</a><h1><?= $editing?'Edit offer':'Add offer' ?></h1><p class="muted">Offers apply automatically at checkout — no code needed. Everything here is re-verified server-side against the live cart.</p></div></section>
<form method="post" action="<?= $editing?'/merchant/offers/'.e($offer['id']):'/merchant/offers' ?>" class="editor-layout" data-offer-form>
<?= csrf_field() ?>
<div class="editor-sections">
<section class="panel form-section"><div class="section-heading"><span>01</span><div><h2>Details</h2><p>Internal name plus an optional customer-facing headline.</p></div></div><div class="form-grid compact-grid"><label>Name<input name="name" value="<?= e($value('name')) ?>" maxlength="120" placeholder="Buy 2 get 1 free — T-shirts" required></label><label>Status<select name="status"><option value="ACTIVE" <?= $value('status','ACTIVE')==='ACTIVE'?'selected':'' ?>>Active</option><option value="INACTIVE" <?= $value('status')==='INACTIVE'?'selected':'' ?>>Inactive</option></select></label><label class="full">Headline <span class="optional">Optional</span><input name="headline" value="<?= e($value('headline')) ?>" maxlength="160" placeholder="Shown on your public offers page — leave blank to auto-generate one"></label></div></section>

<section class="panel form-section"><div class="section-heading"><span>02</span><div><h2>Offer type</h2><p>Choose one mechanic per offer.</p></div></div><div class="form-grid compact-grid"><label class="full">Type<select name="type" data-offer-type><option value="BUY_X_GET_Y" <?= $value('type','BUY_X_GET_Y')==='BUY_X_GET_Y'?'selected':'' ?>>Buy X get Y — one specific product</option><option value="CATEGORY_BUY_N_GET_M" <?= $value('type')==='CATEGORY_BUY_N_GET_M'?'selected':'' ?>>Buy N get M — anywhere in a category</option><option value="FIXED_BUNDLE" <?= $value('type')==='FIXED_BUNDLE'?'selected':'' ?>>Fixed bundle — a set of products at a combined price</option></select></label>
<label class="full" data-offer-field="scope_product_id"><?php $products=$products??[];?>Product<select name="scope_product_id"><option value="0">Choose a product…</option><?php foreach($products as$p):?><option value="<?= e($p['id']) ?>" <?= (int)$value('scope_product_id')===(int)$p['id']?'selected':'' ?>><?= e($p['name']) ?></option><?php endforeach ?></select></label>
<label class="full" data-offer-field="scope_category_id"><?php $categories=$categories??[];?>Category<select name="scope_category_id"><option value="0">Choose a category…</option><?php foreach($categories as$c):?><option value="<?= e($c['id']) ?>" <?= (int)$value('scope_category_id')===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach ?></select></label>
<label data-offer-field="buy_quantity">Buy quantity<input name="buy_quantity" value="<?= e($value('buy_quantity')) ?>" inputmode="numeric" placeholder="e.g. 2"></label>
<label data-offer-field="get_quantity">Get quantity<input name="get_quantity" value="<?= e($value('get_quantity')) ?>" inputmode="numeric" placeholder="e.g. 1"></label>
<label data-offer-field="get_discount_type">The extra items are<select name="get_discount_type"><option value="FREE" <?= $value('get_discount_type','FREE')==='FREE'?'selected':'' ?>>Free</option><option value="PERCENT" <?= $value('get_discount_type')==='PERCENT'?'selected':'' ?>>A percentage off</option></select></label>
<label data-offer-field="get_discount_value">Percentage off <span class="optional">Only if not free</span><input name="get_discount_value" value="<?= e($value('get_discount_value')) ?>" inputmode="decimal" placeholder="e.g. 50"></label>
<label data-offer-field="bundle_price" class="full">Combined bundle price<input name="bundle_price" value="<?= e($value('bundle_price')) ?>" inputmode="decimal" placeholder="e.g. 25.00"></label>
</div>
<div data-offer-field="bundle_items" class="bundle-items"><p class="muted">Add every product and quantity that must be in the cart together for this price. Needs at least two different products.</p><div data-bundle-rows><?php foreach($bundleItems as$i=>$item):?><div class="bundle-row"><select name="bundle_product_id[]"><option value="0">Choose a product…</option><?php foreach($products as$p):?><option value="<?= e($p['id']) ?>" <?= (int)$item['product_id']===(int)$p['id']?'selected':'' ?>><?= e($p['name']) ?></option><?php endforeach ?></select><input name="bundle_quantity[]" value="<?= e($item['quantity']) ?>" inputmode="numeric" placeholder="Qty"><button type="button" class="button compact ghost" data-remove-bundle-row>Remove</button></div><?php endforeach ?></div><button type="button" class="button secondary compact" data-add-bundle-row>+ Add product</button></div>
<template id="bundle-row-template"><div class="bundle-row"><select name="bundle_product_id[]"><option value="0">Choose a product…</option><?php foreach($products as$p):?><option value="<?= e($p['id']) ?>"><?= e($p['name']) ?></option><?php endforeach ?></select><input name="bundle_quantity[]" inputmode="numeric" placeholder="Qty"><button type="button" class="button compact ghost" data-remove-bundle-row>Remove</button></div></template>
</section>

<section class="panel form-section"><div class="section-heading"><span>03</span><div><h2>Active window</h2><p>Leave blank to run indefinitely — useful for holiday offers with a fixed window.</p></div></div><div class="form-grid compact-grid"><label>Starts <span class="optional">Optional</span><input type="datetime-local" name="starts_at" value="<?= e($toLocal($value('starts_at')?:null)) ?>"></label><label>Ends <span class="optional">Optional</span><input type="datetime-local" name="ends_at" value="<?= e($toLocal($value('ends_at')?:null)) ?>"></label></div></section>
</div>
<aside class="editor-actions panel"><strong><?= $editing?'Save offer':'Create offer' ?></strong><p>Changes are validated server-side before they are saved.</p><button class="button primary" type="submit"><?= $editing?'Save changes':'Create offer' ?></button><a class="button secondary" href="/merchant/offers">Cancel</a></aside>
</form>
