<?php
header('Cache-Control: no-store, private');
use App\Support\Color;
header('Referrer-Policy: no-referrer');
$digits=preg_replace('/\D+/','',(string)$store['whatsapp_number']);
$allowedThemes=config('app')['themes'];
$theme=in_array($store['theme'],$allowedThemes,true)?$store['theme']:'modern';
$font=in_array($store['font_key']??'system',['system','editorial','rounded'],true)?$store['font_key']:'system';
$accent=Color::safeHex($store['accent_color']??null);$accentText=Color::contrastText($accent);
$isSuspended=$store['status']==='SUSPENDED';$success=App\Core\Session::pullFlash('success');$error=App\Core\Session::pullFlash('error');
$meta=$meta??[];$metaTitle=$meta['title']??($title.' · '.$store['name']);$metaDescription=$meta['description']??($store['description']?:'Browse '.$store['name'].' and prepare your order for WhatsApp.');$canonical=$meta['canonical']??(config('app')['url'].'/'.$store['slug']);$metaType=$meta['type']??'website';$isIndexable=!$isSuspended&&(bool)($store['search_indexing']??true);$robots=$isIndexable?($meta['robots']??'index,follow'):'noindex,nofollow';if(str_starts_with($robots,'noindex'))header('X-Robots-Tag: '.$robots);$metaImage=$meta['image']??($store['banner_path']?:$store['logo_path']);if($metaImage&&str_starts_with($metaImage,'/'))$metaImage=config('app')['url'].$metaImage;$metaImageAlt=isset($product)?$product['name']:$store['name'];$links=is_array($store['social_links']??null)?$store['social_links']:[];$structuredData=$meta['structured_data']??null;$showBranding=(bool)($store['show_platform_branding']??true);$analyticsPage=isset($product)?'product':(isset($checkoutToken)?'checkout':(isset($catalog)?'store':''));$analyticsProductId=isset($product)?(int)$product['id']:0;$analyticsSearch=isset($query)?(string)$query:'';
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><title><?= e($metaTitle) ?></title><meta name="description" content="<?= e($metaDescription) ?>"><meta name="robots" content="<?= e($robots) ?>"><link rel="canonical" href="<?= e($canonical) ?>"><meta property="og:type" content="<?= e($metaType) ?>"><meta property="og:site_name" content="<?= e($store['name']) ?>"><meta property="og:title" content="<?= e($metaTitle) ?>"><meta property="og:description" content="<?= e($metaDescription) ?>"><meta property="og:url" content="<?= e($canonical) ?>"><?php if($metaImage):?><meta property="og:image" content="<?= e($metaImage) ?>"><meta property="og:image:alt" content="<?= e($metaImageAlt) ?>"><?php endif ?><meta name="twitter:card" content="<?= $metaImage?'summary_large_image':'summary' ?>"><meta name="twitter:title" content="<?= e($metaTitle) ?>"><meta name="twitter:description" content="<?= e($metaDescription) ?>"><?php if($metaImage):?><meta name="twitter:image" content="<?= e($metaImage) ?>"><meta name="twitter:image:alt" content="<?= e($metaImageAlt) ?>"><?php endif ?><?php if(is_array($structuredData)):?><script nonce="<?= e(App\Support\SecurityHeaders::nonce()) ?>" type="application/ld+json"><?= json_encode($structuredData,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script><?php endif ?><link rel="stylesheet" href="/assets/css/storefront.css"></head>
<body class="store-theme-<?= e($theme) ?> store-font-<?= e($font) ?>" style="--accent:<?= e($accent) ?>;--accent-text:<?= e($accentText) ?>" data-store-slug="<?= e($store['slug']) ?>" data-currency="<?= e($store['currency_code']) ?>" data-event-token="<?= e(App\Core\Csrf::token()) ?>" data-analytics-page="<?= e($analyticsPage) ?>" data-analytics-product="<?= e($analyticsProductId) ?>" data-analytics-search="<?= e($analyticsSearch) ?>"><a class="skip-link" href="#store-content">Skip to products</a>
<header class="store-header"><a class="store-identity" href="/<?= e($store['slug']) ?>"><span class="store-logo" aria-hidden="true"><?php if($store['logo_path']):?><img src="<?= e($store['logo_path']) ?>" alt=""><?php else:?><?= e(mb_strtoupper(mb_substr($store['name'],0,1))) ?><?php endif ?></span><span><strong><?= e($store['name']) ?></strong><small><?= $isSuspended?'Store notice':'WhatsApp store' ?></small></span></a><nav aria-label="Store actions"><?php if(!$isSuspended):?><a class="header-action" href="https://wa.me/<?= e($digits) ?>" target="_blank" rel="noopener" aria-label="Contact store on WhatsApp"><span aria-hidden="true">◉</span><span class="action-label">WhatsApp</span></a><?php endif ?><button class="header-action" type="button" data-share-store aria-label="Share store"><span aria-hidden="true">↗</span><span class="action-label">Share</span></button><?php if(!$isSuspended):?><a class="header-action cart-link" href="/<?= e($store['slug']) ?>/cart" aria-label="Open cart"><span aria-hidden="true">Bag</span><span class="cart-count" data-cart-count hidden>0</span></a><?php endif ?></nav></header>
<main id="store-content" class="store-shell"><?php if($success):?><div class="store-notice success" role="status"><?= e($success) ?></div><?php endif ?><?php if($error):?><div class="store-notice error" role="alert"><?= e($error) ?></div><?php endif ?><?= $content ?></main>
<?php if(!$isSuspended):?><nav class="mobile-store-nav" aria-label="Quick store actions"><a href="/<?= e($store['slug']) ?>"><span aria-hidden="true">⌂</span>Shop</a><a href="https://wa.me/<?= e($digits) ?>" rel="noopener"><span aria-hidden="true">◉</span>WhatsApp</a><a href="/<?= e($store['slug']) ?>/cart"><span aria-hidden="true">▢</span>Cart <b data-cart-count hidden>0</b></a></nav><?php endif ?>
<div class="store-toast" data-store-toast role="status" aria-live="polite"></div><footer class="store-footer"><div><strong><?= e($store['name']) ?></strong><?php if(!$isSuspended&&$store['address_text']):?><span><?= e($store['address_text']) ?></span><?php endif ?><?php if(!$isSuspended&&$store['contact_email']):?><a href="mailto:<?= e($store['contact_email']) ?>"><?= e($store['contact_email']) ?></a><?php endif ?><?php if($showBranding):?><a class="powered-by" href="<?= e(config('app')['marketing_url']) ?>" target="_blank" rel="noopener">Powered by <?= e(config('app')['name']) ?></a><?php endif ?></div><?php if(!$isSuspended&&$links):?><nav aria-label="Social links"><?php foreach($links as$network=>$url):?><a href="<?= e($url) ?>" target="_blank" rel="noopener noreferrer"><?= e(ucfirst($network)) ?></a><?php endforeach ?></nav><?php else:?><span><?= $isSuspended?'Please check again later.':'Secure catalog · Order finalized on WhatsApp' ?></span><?php endif ?></footer><script src="/assets/js/storefront.js" defer></script></body></html>
