<?php
namespace App\Repositories;
use App\Core\Database;
final class AdminMerchantRepository
{
    public function search(array$filters):array{$where=" WHERE u.platform_role='MERCHANT' AND u.deleted_at IS NULL";$params=[];if($filters['q']!==''){$where.=" AND (u.name LIKE ? OR u.email LIKE ? OR EXISTS (SELECT 1 FROM store_users sx JOIN stores st ON st.id=sx.store_id WHERE sx.user_id=u.id AND (st.name LIKE ? OR st.slug LIKE ?)))";$like='%'.$filters['q'].'%';array_push($params,$like,$like,$like,$like);}if($filters['status']!==''){$where.=' AND u.status=?';$params[]=$filters['status'];}$pdo=Database::connection();$count=$pdo->prepare('SELECT COUNT(*) FROM users u'.$where);$count->execute($params);$total=(int)$count->fetchColumn();$offset=($filters['page']-1)*25;$sql="SELECT u.id,u.name,u.email,u.status,u.email_verified_at,u.last_login_at,u.created_at,(SELECT COUNT(*) FROM store_users su WHERE su.user_id=u.id AND su.status='ACTIVE') store_count,(SELECT COUNT(*) FROM store_users su JOIN stores s ON s.id=su.store_id WHERE su.user_id=u.id AND su.status='ACTIVE' AND s.status='ACTIVE') active_store_count FROM users u{$where} ORDER BY u.created_at DESC,u.id DESC LIMIT 25 OFFSET {$offset}";$s=$pdo->prepare($sql);$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$filters['page'],'pages'=>max(1,(int)ceil($total/25))];}
    public function find(int$id):?array{$s=Database::connection()->prepare("SELECT id,name,email,status,email_verified_at,password_changed_at,last_login_at,created_at,updated_at FROM users WHERE id=? AND platform_role='MERCHANT' AND deleted_at IS NULL LIMIT 1");$s->execute([$id]);return$s->fetch()?:null;}
    public function stores(int$userId):array{$s=Database::connection()->prepare("SELECT s.id,s.name,s.slug,s.status,s.currency_code,s.created_at,su.role,p.name plan_name,p.code plan_code,sub.status subscription_status,(SELECT COUNT(*) FROM products pr WHERE pr.store_id=s.id AND pr.deleted_at IS NULL) products,(SELECT COUNT(*) FROM categories c WHERE c.store_id=s.id AND c.deleted_at IS NULL) categories,(SELECT COUNT(*) FROM store_users staff WHERE staff.store_id=s.id AND staff.status='ACTIVE' AND staff.role<>'MERCHANT_OWNER') staff,(SELECT COUNT(*) FROM orders o WHERE o.store_id=s.id) orders FROM store_users su JOIN stores s ON s.id=su.store_id LEFT JOIN subscriptions sub ON sub.store_id=s.id LEFT JOIN plans p ON p.id=sub.plan_id WHERE su.user_id=? ORDER BY s.created_at DESC");$s->execute([$userId]);return$s->fetchAll();}
    public function recentAudit(int$userId):array{$s=Database::connection()->prepare("SELECT id,event,target_type,target_id,created_at FROM audit_logs WHERE actor_user_id=? OR (target_type='user' AND target_id=?) ORDER BY created_at DESC,id DESC LIMIT 20");$s->execute([$userId,$userId]);return$s->fetchAll();}
}
