<?php
namespace App\Repositories;
use App\Core\Database;
final class AdminStoreRepository
{
    public function search(array$filters):array{$where=' WHERE 1=1';$params=[];if($filters['q']!==''){$where.=" AND (s.name LIKE ? OR s.slug LIKE ? OR EXISTS (SELECT 1 FROM store_users sx JOIN users ux ON ux.id=sx.user_id WHERE sx.store_id=s.id AND sx.role='MERCHANT_OWNER' AND (ux.name LIKE ? OR ux.email LIKE ?)))";$like='%'.$filters['q'].'%';array_push($params,$like,$like,$like,$like);}if($filters['status']!==''){$where.=' AND s.status=?';$params[]=$filters['status'];}if($filters['plan']!==''){$where.=' AND p.code=?';$params[]=$filters['plan'];}$joins=' FROM stores s LEFT JOIN subscriptions sub ON sub.store_id=s.id LEFT JOIN plans p ON p.id=sub.plan_id';$pdo=Database::connection();$count=$pdo->prepare('SELECT COUNT(*)'.$joins.$where);$count->execute($params);$total=(int)$count->fetchColumn();$offset=($filters['page']-1)*25;$ownerId="(SELECT ux.id FROM store_users sx JOIN users ux ON ux.id=sx.user_id WHERE sx.store_id=s.id AND sx.role='MERCHANT_OWNER' AND sx.status='ACTIVE' ORDER BY sx.id LIMIT 1)";$ownerName="(SELECT ux.name FROM store_users sx JOIN users ux ON ux.id=sx.user_id WHERE sx.store_id=s.id AND sx.role='MERCHANT_OWNER' AND sx.status='ACTIVE' ORDER BY sx.id LIMIT 1)";$ownerEmail="(SELECT ux.email FROM store_users sx JOIN users ux ON ux.id=sx.user_id WHERE sx.store_id=s.id AND sx.role='MERCHANT_OWNER' AND sx.status='ACTIVE' ORDER BY sx.id LIMIT 1)";$sql="SELECT s.id,s.name,s.slug,s.status,s.currency_code,s.country_code,s.created_at,p.code plan_code,p.name plan_name,sub.status subscription_status,{$ownerId} owner_id,{$ownerName} owner_name,{$ownerEmail} owner_email,(SELECT COUNT(*) FROM products pr WHERE pr.store_id=s.id AND pr.deleted_at IS NULL) products,(SELECT COUNT(*) FROM orders o WHERE o.store_id=s.id) orders".$joins.$where." ORDER BY s.created_at DESC,s.id DESC LIMIT 25 OFFSET {$offset}";$s=$pdo->prepare($sql);$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$filters['page'],'pages'=>max(1,(int)ceil($total/25))];}
    public function find(int$id):?array{$s=Database::connection()->prepare("SELECT s.*,p.id plan_id,p.code plan_code,p.name plan_name,p.monthly_price,p.currency_code plan_currency,sub.id subscription_id,sub.status subscription_status,sub.current_period_ends_at,sub.trial_ends_at,sub.grace_ends_at,sub.provider FROM stores s LEFT JOIN subscriptions sub ON sub.store_id=s.id LEFT JOIN plans p ON p.id=sub.plan_id WHERE s.id=? LIMIT 1");$s->execute([$id]);return$s->fetch()?:null;}
    public function members(int$storeId):array{$s=Database::connection()->prepare("SELECT u.id,u.name,u.email,u.status user_status,su.role,su.status membership_status,su.created_at FROM store_users su JOIN users u ON u.id=su.user_id WHERE su.store_id=? ORDER BY FIELD(su.role,'MERCHANT_OWNER','MERCHANT_ADMIN','ORDER_MANAGER','STAFF'),u.name");$s->execute([$storeId]);return$s->fetchAll();}
    public function metrics(int$storeId):array{$s=Database::connection()->prepare("SELECT (SELECT COUNT(*) FROM products WHERE store_id=? AND deleted_at IS NULL) products,(SELECT COUNT(*) FROM categories WHERE store_id=? AND deleted_at IS NULL) categories,(SELECT COUNT(*) FROM customers WHERE store_id=?) customers,(SELECT COUNT(*) FROM orders WHERE store_id=?) orders,(SELECT COALESCE(SUM(total),0) FROM orders WHERE store_id=? AND status<>'CANCELLED') order_value");$s->execute([$storeId,$storeId,$storeId,$storeId,$storeId]);return$s->fetch()?:[];}
    public function recentOrders(int$storeId):array{$s=Database::connection()->prepare('SELECT reference,customer_name,currency_code,total,status,placed_at FROM orders WHERE store_id=? ORDER BY placed_at DESC,id DESC LIMIT 10');$s->execute([$storeId]);return$s->fetchAll();}
    public function subscriptionEvents(int$storeId):array{$s=Database::connection()->prepare('SELECT e.event_type,e.from_status,e.to_status,e.created_at,fp.code from_plan,tp.code to_plan FROM subscription_events e LEFT JOIN plans fp ON fp.id=e.from_plan_id LEFT JOIN plans tp ON tp.id=e.to_plan_id WHERE e.store_id=? ORDER BY e.created_at DESC,e.id DESC LIMIT 15');$s->execute([$storeId]);return$s->fetchAll();}
}
