<?php
namespace App\Repositories;

use App\Core\Database;
use App\Support\Money;
use App\Services\PlanAccessService;

final class StorefrontRepository
{
    public function publicProductId(int$storeId,int$productId):bool{$s=Database::connection()->prepare("SELECT 1 FROM products p LEFT JOIN categories c ON c.id=p.category_id AND c.store_id=p.store_id WHERE p.id=? AND p.store_id=? AND p.status='ACTIVE' AND p.deleted_at IS NULL AND (p.category_id IS NULL OR c.status='ACTIVE')");$s->execute([$productId,$storeId]);return(bool)$s->fetchColumn();}
    public function storeBySlug(string $slug):?array{$s=Database::connection()->prepare("SELECT s.id,s.name,s.slug,s.whatsapp_number,s.country_code,s.currency_code,s.theme,s.status,s.logo_path,s.banner_path,s.accent_color,s.font_key,s.description,s.seo_title,s.seo_description,s.search_indexing,s.contact_email,s.address_text,s.social_links,s.offers_page_enabled FROM stores s WHERE s.slug=? AND s.status IN ('ACTIVE','SUSPENDED') LIMIT 1");$s->execute([$slug]);$store=$s->fetch();if(!$store)return null;$links=json_decode((string)($store['social_links']??''),true);$access=(new PlanAccessService)->context((int)$store['id'],null,false,false);$store['social_links']=is_array($links)?$links:[];$store['plan_features']=$access['features'];$store['plan_code']=$access['plan']['code'];$store['show_platform_branding']=!($access['features']['remove_platform_branding']??false);return$store;}
    public function redirectTarget(string$oldSlug):?string{$s=Database::connection()->prepare('SELECT st.slug FROM store_slug_redirects r JOIN stores st ON st.id=r.store_id WHERE r.old_slug=? LIMIT 1');$s->execute([$oldSlug]);$slug=$s->fetchColumn();return is_string($slug)?$slug:null;}
    public function categories(int $storeId):array{$s=Database::connection()->prepare("SELECT c.*,(SELECT COUNT(*) FROM products p WHERE p.category_id=c.id AND p.store_id=c.store_id AND p.status='ACTIVE' AND p.deleted_at IS NULL) product_count FROM categories c WHERE c.store_id=? AND c.status='ACTIVE' AND c.deleted_at IS NULL ORDER BY c.sort_order,c.name");$s->execute([$storeId]);return$s->fetchAll();}
    public function catalog(int $storeId,string $query,?int $categoryId,int $page=1):array
    {
        $where=" WHERE p.store_id=? AND p.status='ACTIVE' AND p.deleted_at IS NULL AND (p.category_id IS NULL OR c.status='ACTIVE')";$params=[$storeId];if($query!==''){$where.=' AND (p.name LIKE ? OR p.sku LIKE ? OR p.description LIKE ? OR c.name LIKE ?)';$like='%'.$query.'%';array_push($params,$like,$like,$like,$like);}if($categoryId){$where.=' AND p.category_id=?';$params[]=$categoryId;}
        $count=Database::connection()->prepare('SELECT COUNT(*) FROM products p LEFT JOIN categories c ON c.id=p.category_id AND c.store_id=p.store_id'.$where);$count->execute($params);$total=(int)$count->fetchColumn();$page=max(1,$page);$pages=max(1,(int)ceil($total/24));$offset=($page-1)*24;
        $sql="SELECT p.id,p.name,p.slug,p.sku,p.price,p.compare_price,p.availability,p.is_featured,c.name category_name,(SELECT COALESCE(pi.thumbnail_path,pi.path) FROM product_images pi WHERE pi.product_id=p.id AND pi.store_id=p.store_id ORDER BY pi.sort_order,pi.id LIMIT 1) image,(SELECT COUNT(*) FROM product_variants pv WHERE pv.product_id=p.id AND pv.store_id=p.store_id) variant_count FROM products p LEFT JOIN categories c ON c.id=p.category_id AND c.store_id=p.store_id{$where} ORDER BY p.is_featured DESC,p.created_at DESC LIMIT 24 OFFSET {$offset}";
        $s=Database::connection()->prepare($sql);$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>$pages];
    }
    public function featured(int $storeId):array{$s=Database::connection()->prepare("SELECT p.id,p.name,p.slug,p.price,p.compare_price,p.availability,c.name category_name,(SELECT COALESCE(pi.thumbnail_path,pi.path) FROM product_images pi WHERE pi.product_id=p.id AND pi.store_id=p.store_id ORDER BY pi.sort_order,pi.id LIMIT 1) image,(SELECT COUNT(*) FROM product_variants pv WHERE pv.product_id=p.id AND pv.store_id=p.store_id) variant_count FROM products p LEFT JOIN categories c ON c.id=p.category_id AND c.store_id=p.store_id WHERE p.store_id=? AND p.status='ACTIVE' AND p.is_featured=1 AND p.deleted_at IS NULL AND (p.category_id IS NULL OR c.status='ACTIVE') ORDER BY p.updated_at DESC LIMIT 8");$s->execute([$storeId]);return$s->fetchAll();}
    public function categoryBySlug(int $storeId,string $slug):?array{$s=Database::connection()->prepare("SELECT * FROM categories WHERE store_id=? AND slug=? AND status='ACTIVE' AND deleted_at IS NULL");$s->execute([$storeId,$slug]);return$s->fetch()?:null;}
    public function product(int $storeId,string $slug):?array
    {
        $s=Database::connection()->prepare("SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id AND c.store_id=p.store_id WHERE p.store_id=? AND p.slug=? AND p.status='ACTIVE' AND p.deleted_at IS NULL AND (p.category_id IS NULL OR c.status='ACTIVE') LIMIT 1");$s->execute([$storeId,$slug]);$product=$s->fetch();if(!$product)return null;$productId=(int)$product['id'];
        $images=Database::connection()->prepare('SELECT id,path,thumbnail_path,width,height FROM product_images WHERE store_id=? AND product_id=? ORDER BY sort_order,id');$images->execute([$storeId,$productId]);$product['images']=$images->fetchAll();
        $options=Database::connection()->prepare('SELECT id,name FROM product_options WHERE store_id=? AND product_id=? ORDER BY sort_order,id');$options->execute([$storeId,$productId]);$product['options']=$options->fetchAll();$valuesByOption=[];if($product['options']){$ids=array_map('intval',array_column($product['options'],'id'));$marks=implode(',',array_fill(0,count($ids),'?'));$values=Database::connection()->prepare("SELECT id,option_id,value FROM product_option_values WHERE store_id=? AND option_id IN ({$marks}) ORDER BY option_id,sort_order,id");$values->execute(array_merge([$storeId],$ids));foreach($values->fetchAll()as$value)$valuesByOption[(int)$value['option_id']][]=$value;}foreach($product['options']as&$option)$option['values']=$valuesByOption[(int)$option['id']]??[];unset($option);
        $variants=Database::connection()->prepare('SELECT id,label,sku,price_adjustment,stock_quantity,is_available FROM product_variants WHERE store_id=? AND product_id=? ORDER BY id');$variants->execute([$storeId,$productId]);$product['variants']=$variants->fetchAll();$map=Database::connection()->prepare('SELECT variant_id,option_value_id FROM product_variant_values WHERE store_id=? AND variant_id IN (SELECT id FROM product_variants WHERE store_id=? AND product_id=?) ORDER BY option_value_id');$map->execute([$storeId,$storeId,$productId]);$valuesByVariant=[];foreach($map->fetchAll()as$row)$valuesByVariant[(int)$row['variant_id']][]=(int)$row['option_value_id'];foreach($product['variants']as&$variant){$variant['value_ids']=$valuesByVariant[(int)$variant['id']]??[];$variant['final_price']=Money::add($product['price'],$variant['price_adjustment']);$variant['purchasable']=(bool)$variant['is_available']&&($variant['stock_quantity']===null||(int)$variant['stock_quantity']>0)&&$product['availability']==='AVAILABLE';}unset($variant);return$product;
    }
    public function related(int $storeId,int $productId,?int $categoryId):array{$params=[$storeId,$productId];$where='p.store_id=? AND p.id<>?';if($categoryId){$where.=' AND p.category_id=?';$params[]=$categoryId;}$s=Database::connection()->prepare("SELECT p.id,p.name,p.slug,p.price,p.compare_price,p.availability,(SELECT COALESCE(pi.thumbnail_path,pi.path) FROM product_images pi WHERE pi.product_id=p.id AND pi.store_id=p.store_id ORDER BY pi.sort_order,pi.id LIMIT 1) image,(SELECT COUNT(*) FROM product_variants pv WHERE pv.product_id=p.id AND pv.store_id=p.store_id) variant_count FROM products p LEFT JOIN categories c ON c.id=p.category_id AND c.store_id=p.store_id WHERE {$where} AND p.status='ACTIVE' AND p.deleted_at IS NULL AND (p.category_id IS NULL OR c.status='ACTIVE') ORDER BY p.is_featured DESC,p.updated_at DESC LIMIT 4");$s->execute($params);return$s->fetchAll();}
}
