'use client';
import {useEffect,useState} from 'react';
import {Package,Search,Plus,Settings,LogOut,ShieldCheck,Layers,CheckCheck,PackageX,ArrowUpRight,Download,RefreshCw,Trash2,ImagePlus,Eye,EyeOff,SlidersHorizontal,LockKeyhole,Check,Upload,FileText} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {categories,matches,Product,bottleSizes} from './model';
async function api(action?:string,data:object={}){const r=await fetch('/api/inventory'+(action?'':'?view=status'),action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})}:{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw Error(j.error||'Request failed.');return j}
function Password({label,value,onChange,autoComplete='current-password'}:{label:string;value:string;onChange:(s:string)=>void;autoComplete?:string}){const[show,setShow]=useState(false);return <label className="field">{label}<div className="relative"><input required maxLength={128} type={show?'text':'password'} autoComplete={autoComplete} value={value} onChange={e=>onChange(e.target.value)} style={{paddingRight:44}}/><button type="button" className="absolute right-3 top-3 text-muted-foreground" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>}
function CategoryPicker({value,onChange,all=false,container}:{value:string;onChange:(s:string)=>void;all?:boolean;container?:HTMLElement|null}){const items=all?['All categories',...categories]:categories;return <Combobox items={items} value={value} onValueChange={v=>onChange(v|| (all?'All categories':categories[0]))} filter={(item,q)=>matches(item,q)}><ComboboxInput aria-label="Search categories" placeholder="Search categories…" className="min-w-56 bg-white"/><ComboboxContent container={container}><ComboboxEmpty>No matching categories</ComboboxEmpty><ComboboxList>{(item:string)=><ComboboxItem key={item} value={item}>{item}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox>}
function BrandLogo(){return <div className="brand-logo"><img src="/huqa-logo.jpeg" alt="HUQA.LB — Arguileh & Vapes" width={819} height={819}/></div>}
function ProductCategoryPicker({value,onChange}:{value:string;onChange:(s:string)=>void}){
 const group=value.split(' / ')[0];const groups=[...new Set(categories.map(c=>c.split(' / ')[0]))];const options=categories.filter(c=>c.startsWith(group+' / '));if(value==='Disposables / 0mg')options.push(value);
 return <div className="product-category-fields"><div className="field"><label>Category</label><Select value={group} onValueChange={g=>onChange(categories.find(c=>c===g||c.startsWith(g+' / '))!)}><SelectTrigger aria-label="Product category" className="category-choice"><SelectValue placeholder="Choose category"/></SelectTrigger><SelectContent>{groups.map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select></div>{options.length>0&&<div className="field"><label>{group==='Liquids'?'Nicotine strength':'Type'}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={group==='Liquids'?'Nicotine strength':'Product type'} className="category-choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(c=><SelectItem key={c} value={c}>{c==='Disposables / 0mg'?'0mg (existing product)':c.split(' / ')[1]}</SelectItem>)}</SelectContent></Select></div>}</div>
}
const fresh=(category:string):Product=>({id:'',name:'',brand:'',category:categories.includes(category)?category:categories[0],bottleSize:'',description:'',image:'',revision:0,updatedAt:0,variants:[{id:crypto.randomUUID(),label:'',strength:'',available:true}]});
export default function Dashboard(){
 const[recover,setRecover]=useState(false),[recoveryInput,setRecoveryInput]=useState(''),[recoveryCode,setRecoveryCode]=useState('');
 const[status,setStatus]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState('');
 const[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState('All categories'),[availability,setAvailability]=useState('all'),[brand,setBrand]=useState('all');
 const[bottleSizeFilter,setBottleSizeFilter]=useState('all');
 const[editorPortal,setEditorPortal]=useState<HTMLDivElement|null>(null);
 const[editor,setEditor]=useState<Product|null>(null),[editorError,setEditorError]=useState(''),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[removing,setRemoving]=useState<Product|null>(null),[uploading,setUploading]=useState(false);
 const[settings,setSettings]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[newUsername,setNewUsername]=useState(''),[settingsError,setSettingsError]=useState('');
 async function check(){setError('');try{const s=await api();setStatus(s);if(s.loggedIn){setNewUsername(s.username);await refresh()}}catch(e){setError((e as Error).message)}}
 async function refresh(){setLoading(true);try{const r=await fetch('/api/inventory',{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw Error(j.error);setProducts(j.products)}catch(e){toast.error((e as Error).message);setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{check()},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool||!status?.loggedIn)return;const life=new AbortController();try{Promise.resolve(ctx.registerTool({name:'filter_inventory',description:'Filter the visible inventory by a search phrase without modifying product records.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw Error('Provide a search phrase of up to 200 characters.');setQuery(input.query);setCategory('All categories');(setBrand('all'),setBottleSizeFilter('all'));setAvailability('all');await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {query:input.query,matchingProducts:products.filter(p=>matches([p.name,p.brand,p.category,p.bottleSize||'',...p.variants.map(v=>v.label+' '+v.strength)].join(' '),input.query)).map(p=>({id:p.id,name:p.name}))}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[status?.loggedIn,products]);
 useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty]);
 function patch(p:Partial<Product>){setEditor(v=>v?{...v,...p}:null);setDirty(true)}
 function edit(p:Product){setEditor(structuredClone(p));setDirty(false);setEditorError('')}
 async function save(){if(!editor)return;setBusy(true);setEditorError('');try{const j=await api('save',{product:editor});setProducts(ps=>[j.product,...ps.filter(p=>p.id!==j.product.id)]);setEditor(null);setDirty(false);toast.success('Product saved')}catch(e){setEditorError((e as Error).message)}finally{setBusy(false)}}
 async function upload(f?:File){if(!f)return;setUploading(true);setEditorError('');try{if(f.size>5000000)throw Error('Choose an image under 5 MB.');const form=new FormData();form.set('file',f);const r=await fetch('/api/image',{method:'POST',body:form});const j:any=await r.json();if(!r.ok)throw Error(j.error);patch({image:j.url})}catch(e){setEditorError((e as Error).message)}finally{setUploading(false)}}
 const variants=products.flatMap(p=>p.variants),available=variants.filter(v=>v.available).length;
 const brands=[...new Set(products.filter(p=>category==='All categories'||p.category===category).map(p=>p.brand).filter(Boolean))].sort();
 const filtered=products.filter(p=>(category==='All categories'||p.category===category)&&(brand==='all'||p.brand===brand)&&(bottleSizeFilter==='all'||(p.category.startsWith('Liquids / ')&&p.bottleSize===bottleSizeFilter))&&(availability==='all'||(availability==='unavailable'?p.variants.some(v=>!v.available):p.variants.some(v=>v.available)))&&matches([p.name,p.brand,p.category,p.bottleSize||'',...p.variants.map(v=>v.label+' '+v.strength)].join(' '),query));
 const recoveryDialog=<Dialog open={!!recoveryCode}><DialogContent showCloseButton={false}><DialogHeader><DialogTitle>Save your recovery code</DialogTitle><DialogDescription>Keep this code somewhere safe. It can reset your admin password through your private workspace. It is shown only once; any previous code no longer works.</DialogDescription></DialogHeader><code className="block text-sm break-all bg-muted p-4 rounded-lg select-all">{recoveryCode}</code><Button onClick={async()=>{try{await navigator.clipboard.writeText(recoveryCode);toast.success('Recovery code copied')}catch{toast.error('Select and copy the code manually.')}}}>Copy code</Button><Button variant="outline" onClick={()=>setRecoveryCode('')}>I have saved the code</Button></DialogContent></Dialog>;
 if(!status||!status.loggedIn)return <><Toaster/>{recoveryDialog}<div className="auth-shell"><section className="auth-brand"><div><BrandLogo/><p className="text-sm text-slate-400 mt-2">INVENTORY WORKSPACE</p></div><div className="auth-story"><div className="h-px w-14 bg-[#d2f694] mb-8"/><h1 className="text-5xl font-medium leading-tight max-w-md">Every product.<br/>Every variant.<br/><span className="text-[#d2f694]">One workspace.</span></h1><p className="text-slate-400 mt-7 max-w-sm leading-relaxed">Keep product details and availability organized in your private inventory.</p></div><p className="flex gap-2 items-center text-sm text-slate-400 mt-6"><ShieldCheck size={17}/> Private admin access</p></section><section className="auth-form"><div className="iconbox mb-7"><LockKeyhole size={22}/></div><h2 className="page-title">{recover?'Recover admin access':status?.setup?'Set up your admin account':status?'Welcome back':'Opening your workspace'}</h2><p className="quiet mt-3 mb-8">{status?.setup?'Choose your username and a password of at least 12 characters. Setup is available only through your private workspace.':'Sign in to manage products and availability.'}</p>{error&&<p role="alert" className="error mb-5">{error}</p>}{status?<form className="space-y-5" onSubmit={async e=>{e.preventDefault();setError('');if((status.setup||recover)&&password!==confirmation){setError('Passwords do not match.');return}setBusy(true);try{const result=await api(recover?'recover':status.setup?'setup':'login',{username,password,recoveryCode:recoveryInput});if(result.recoveryCode)setRecoveryCode(result.recoveryCode);setRecover(false);setRecoveryInput('');setPassword('');setConfirmation('');await check()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Username<input required minLength={3} maxLength={40} autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Your admin username"/></label>{recover&&<label className="field">Recovery code<input required value={recoveryInput} onChange={e=>setRecoveryInput(e.target.value)} autoComplete="off"/></label>}<Password label={recover?'New password':'Password'} value={password} onChange={setPassword} autoComplete={status.setup?'new-password':'current-password'}/>{(status.setup||recover)&&<Password label="Confirm password" value={confirmation} onChange={setConfirmation} autoComplete="new-password"/>}<Button disabled={busy} className="w-full h-12">{busy?'Please wait…':recover?'Reset admin account':status.setup?'Create admin account':'Sign in'}<ArrowUpRight size={18}/></Button>{!status.setup&&<button type="button" className="text-sm underline w-full text-center" onClick={()=>{setRecover(!recover);setError('')}}>{recover?'Back to sign in':'Forgot password? Use your recovery code'}</button>}<p className="quiet text-center">HUQA · Internal inventory</p></form>:error?<Button onClick={check}>Retry</Button>:<Skeleton className="h-12 w-full"/>}</section></div></>;
 return <SidebarProvider>{recoveryDialog}<Toaster position="top-right"/><Sidebar><SidebarHeader className="compact-sidebar-brand border-b border-sidebar-border"><BrandLogo/><p className="text-xs tracking-wider text-slate-400 leading-relaxed">INVENTORY<br/>WORKSPACE</p></SidebarHeader><SidebarContent className="inventory-navigation"><SidebarGroup className="px-4 pt-4"><SidebarGroupLabel className="text-slate-400 text-xs tracking-wider mb-3">WORKSPACE</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive onClick={()=>{setCategory('All categories');setQuery('');setAvailability('all');(setBrand('all'),setBottleSizeFilter('all'))}} className="h-11 px-3"><Package/><span>Inventory</span><span className="ml-auto text-xs">{products.length}</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton onClick={()=>{setAvailability('unavailable');setCategory('All categories');(setBrand('all'),setBottleSizeFilter('all'));setQuery('')}} className="h-11 px-3"><PackageX/><span>Unavailable variants</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup><SidebarGroup className="px-4 pt-3"><SidebarGroupLabel className="text-slate-400 text-xs tracking-wider mb-3">CATEGORIES</SidebarGroupLabel><SidebarMenu>{['Disposables','Machines','Coils & accessories','Liquids','Nicotine pouches'].map(c=><SidebarMenuItem key={c}><SidebarMenuButton className="h-10 px-3" onClick={()=>{setCategory('All categories');(setBrand('all'),setBottleSizeFilter('all'));setQuery(c);setAvailability('all')}}><Layers size={17}/><span>{c}</span><span className="ml-auto text-xs text-slate-400">{products.filter(p=>p.category.startsWith(c)).length}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter className="p-4 border-t border-sidebar-border"><SidebarMenu><SidebarMenuItem><SidebarMenuButton className="h-11" onClick={()=>{setSettingsError('');setSettings(true)}}><Settings/><span>Admin settings</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton className="h-11" onClick={async()=>{try{await api('logout');setProducts([]);setStatus({...status,loggedIn:false})}catch(e){toast.error((e as Error).message)}}}><LogOut/><span>Sign out</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="flex gap-3 items-center px-2 pt-4 pb-2"><div className="h-9 w-9 rounded-full grid place-items-center bg-[#d2f694] text-[#203020] font-bold">{status.username?.[0]?.toUpperCase()}</div><div><p className="text-sm">{status.username}</p><p className="text-xs text-slate-400">Administrator</p></div></div></SidebarFooter></Sidebar>
 <SidebarInset className="min-w-0 bg-background"><header className="h-[76px] flex items-center justify-between px-5 md:px-10 border-b bg-white gap-4"><div className="flex items-center gap-4"><SidebarTrigger/><span className="quiet">Workspace <span className="mx-3 text-slate-300">/</span><span className="text-foreground">Inventory</span></span></div><span className="flex gap-2 items-center text-sm text-muted-foreground"><ShieldCheck size={16}/><span className="hidden sm:inline">Private workspace</span></span></header>
 <main className="p-5 md:p-10 max-w-[1600px] w-full mx-auto"><div className="flex flex-wrap justify-between gap-4 items-center mb-8"><div><p className="text-xs uppercase tracking-[.15em] text-muted-foreground mb-3">Product management</p><h1 className="page-title">Your inventory</h1><p className="quiet mt-2">Manage products, variants and availability.</p></div><Button className="h-11 px-5" onClick={()=>edit(fresh(category))}><Plus size={18}/>Add product</Button></div>
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-8">{[[Package,'Products',products.length],[Layers,'Variants',variants.length],[CheckCheck,'In stock',available],[PackageX,'Out of stock',variants.length-available]].map(([Icon,label,count]:any)=><div className="stat" key={label}><div className="flex justify-between items-center"><span>{label}</span><Icon size={18} className="text-muted-foreground"/></div><strong>{count.toString().padStart(2,'0')}</strong></div>)}</div>
 {error&&<div role="alert" className="error mb-5">{error} <button className="underline" onClick={()=>{setError('');refresh()}}>Retry</button></div>}
 <section className="panel overflow-hidden"><div className="p-5 md:p-6 border-b"><div className="flex justify-between items-center mb-5"><h2 className="text-lg font-semibold">All products <span className="ml-2 text-sm text-muted-foreground font-normal">{filtered.length}</span></h2><Button variant="ghost" size="icon" aria-label="Refresh inventory" disabled={loading} onClick={()=>{setError('');refresh()}}><RefreshCw size={17} className={loading?'animate-spin':''}/></Button></div><div className="toolbar"><div className="relative flex-1 min-w-52"><Search size={18} className="absolute top-3 left-3 text-muted-foreground"/><input aria-label="Search products" placeholder="Search products, brands or flavors…" value={query} onChange={e=>setQuery(e.target.value)} style={{paddingLeft:39}}/></div><CategoryPicker all value={category} onChange={c=>{setCategory(c);(setBrand('all'),setBottleSizeFilter('all'))}}/><Select value={availability} onValueChange={setAvailability}><SelectTrigger className="h-11 bg-white w-44"><SlidersHorizontal size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All availability</SelectItem><SelectItem value="available">In stock</SelectItem><SelectItem value="unavailable">Out of stock</SelectItem></SelectContent></Select>{brands.length>0&&<Select value={brand} onValueChange={setBrand}><SelectTrigger className="h-11 w-40 bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All brands</SelectItem>{brands.map(b=><SelectItem key={b} value={b}>{b}</SelectItem>)}</SelectContent></Select>}{(bottleSizeFilter!=='all'||products.some(p=>p.category.startsWith('Liquids / ')&&(category==='All categories'||p.category===category)&&(brand==='all'||p.brand===brand)))&&<Select value={bottleSizeFilter} onValueChange={setBottleSizeFilter}><SelectTrigger aria-label="Filter by bottle size" className="h-11 w-40 bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All bottle sizes</SelectItem>{bottleSizes.map(size=><SelectItem key={size} value={size}>{size}</SelectItem>)}</SelectContent></Select>}</div>{query&&<p className="quiet mt-3">Results include close spelling matches. <button className="underline ml-2" onClick={()=>setQuery('')}>Clear search</button></p>}</div>
 {loading?<div className="p-6 space-y-4"><Skeleton className="h-14"/><Skeleton className="h-14"/><Skeleton className="h-14"/></div>:filtered.length?<Table><TableHeader><TableRow className="bg-[#fafbfc]"><TableHead className="pl-6 h-12">Product</TableHead><TableHead>Category</TableHead><TableHead>Price</TableHead><TableHead>Variants</TableHead><TableHead>Availability</TableHead><TableHead>Updated</TableHead><TableHead className="text-right pr-6">Manage</TableHead></TableRow></TableHeader><TableBody>{filtered.map(p=><TableRow key={p.id} className="h-24"><TableCell className="pl-6"><button className="table-product text-left" onClick={()=>edit(p)}>{p.image?<img src={p.image} alt=""/>:<span className="iconbox"><Package size={20}/></span>}<span><strong>{p.name}</strong><small>{p.brand||'No brand'}{p.category.startsWith('Liquids / ')?' · '+(p.bottleSize||'Size not set'):''}</small></span></button></TableCell><TableCell className="text-sm max-w-56 whitespace-normal">{p.category}</TableCell><TableCell className="whitespace-nowrap">{typeof p.price==='number'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(p.price):'Price not set'}</TableCell><TableCell>{p.variants.length}</TableCell><TableCell><span className={'badge '+(p.variants.every(v=>!v.available)?'off':'')}>{p.variants.filter(v=>v.available).length} / {p.variants.length} in stock</span></TableCell><TableCell className="quiet">{new Date(p.updatedAt).toLocaleDateString()}</TableCell><TableCell className="pr-6 text-right"><Button variant="outline" onClick={()=>edit(p)}>Edit</Button></TableCell></TableRow>)}</TableBody></Table>:<Empty className="py-20"><EmptyHeader><div className="iconbox mx-auto mb-3 w-14 h-14"><Package size={26}/></div><EmptyTitle>{products.length?'No matching products':'A fresh start for your inventory'}</EmptyTitle><EmptyDescription>{products.length?'Try a different search or clear your filters.':'Your categories are ready. Add your first product, then create its variants and set availability.'}</EmptyDescription></EmptyHeader><Button onClick={()=>products.length?(setQuery(''),setCategory('All categories'),(setBrand('all'),setBottleSizeFilter('all')),setAvailability('all')):edit(fresh(category))}>{products.length?'Clear filters':<><Plus size={17}/>Add first product</>}</Button></Empty>}
 <div className="px-6 py-4 border-t flex flex-wrap gap-3 justify-between quiet"><span>{filtered.length} product{filtered.length!==1?'s':''} · {category}</span><span>Availability is managed per variant</span></div></section><p className="quiet flex items-center gap-2 mt-5"><ShieldCheck size={15}/> Product changes are saved with an automatic history snapshot.</p></main></SidebarInset>
 <Sheet open={!!editor} onOpenChange={open=>{if(!open&&!busy&&!uploading){if(dirty)setDiscard(true);else setEditor(null)}}}>
  <SheetContent ref={setEditorPortal} className="product-editor w-full sm:max-w-[920px] h-dvh max-h-dvh p-0 gap-0 overflow-hidden">
   <SheetHeader className="editor-heading shrink-0">
    <div className="editor-heading-icon"><Package size={23}/></div>
    <div><p className="editor-eyebrow">Inventory / Product editor</p><SheetTitle className="editor-title">{editor?.id?'Edit product':'New product'}</SheetTitle><SheetDescription className="editor-subtitle">Details, imagery and availability in one place.</SheetDescription></div>
   </SheetHeader>
   {editor&&<form onSubmit={e=>{e.preventDefault();save()}} className="flex min-h-0 flex-1 flex-col">
    <div className="editor-scroll min-h-0 flex-1 overflow-y-auto overscroll-contain touch-pan-y" data-editor-scroll>
     <div className="editor-overview-grid">
      <section className="editor-card" aria-labelledby="details-heading">
       <div className="editor-section-heading"><span className="section-number">01</span><div><h3 id="details-heading">Product details</h3><p>The essentials for your inventory.</p></div></div>
       <div className="editor-fields">
        <label className="field">Product name <input required maxLength={150} placeholder="Give your product a name" value={editor.name} onChange={e=>patch({name:e.target.value})}/></label>
        <label className="field">Price (USD)<input required type="number" min="0" max="1000000" step="0.01" inputMode="decimal" placeholder="e.g. 12.50" value={editor.price??''} onChange={e=>patch({price:e.target.value===''?undefined:Number(e.target.value)})}/></label>
        <ProductCategoryPicker value={editor.category} onChange={category=>patch({category,bottleSize:category.startsWith('Liquids / ')?(editor.bottleSize||''):''})}/>
        {editor.category.startsWith('Liquids / ')&&<div className="field"><label>Bottle size</label><Select value={editor.bottleSize||''} onValueChange={bottleSize=>patch({bottleSize})}><SelectTrigger aria-label="Bottle size" className="category-choice"><SelectValue placeholder="Choose bottle size"/></SelectTrigger><SelectContent>{bottleSizes.map(size=><SelectItem value={size} key={size}>{size}</SelectItem>)}</SelectContent></Select></div>}
        <label className="field"><span>Brand <span className="field-optional">Optional</span></span><input maxLength={100} placeholder="Enter brand name" value={editor.brand} onChange={e=>patch({brand:e.target.value})}/></label>
       </div>
      </section>
      <section className="editor-card image-card" aria-labelledby="image-heading">
       <div className="editor-section-heading"><span className="section-number">02</span><div><h3 id="image-heading">Product image</h3><p>A clear view of your product.</p></div></div>
       <label className={'image-upload '+(editor.image?'has-image':'')}>
        {editor.image?<img src={editor.image} alt="Product preview"/>:<><span className="upload-icon"><ImagePlus size={27} strokeWidth={1.5}/></span><strong>{uploading?'Uploading image…':'Add product image'}</strong><span>Choose a file from your device</span></>}
        <input type="file" aria-label={editor.image?'Replace product image':'Upload product image'} accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/>
        {editor.image&&<span className="replace-image"><Upload size={15}/>{uploading?'Uploading…':'Replace image'}</span>}
       </label>
       <div className="image-caption"><span>JPG, PNG or WebP · Max 5 MB</span>{editor.image&&<Button type="button" size="icon" variant="ghost" aria-label="Remove image" disabled={uploading} onClick={()=>patch({image:''})}><Trash2 size={15}/></Button>}</div>
      </section>
     </div>
     <section className="editor-card description-card"><label className="field"><span className="description-label"><FileText size={17}/>Description <span className="field-optional">Optional</span></span><textarea rows={3} maxLength={3000} placeholder="Add specifications, product details or internal notes…" value={editor.description} onChange={e=>patch({description:e.target.value})}/></label></section>
     <section className="editor-card variants-section" aria-labelledby="variants-heading">
      <div className="variants-section-top"><div className="editor-section-heading"><span className="section-number">03</span><div><h3 id="variants-heading">Variants & availability <span className="variant-count">{editor.variants.length}</span></h3><p>{editor.category==='Machines'?'A separate variant for each color.':editor.category==='Nicotine pouches'?'Each flavor and strength combination. Up to two strengths per model.':editor.category.includes('Coils')?'A separate variant for each coil or pod option.':'A separate variant for each flavor.'}</p></div></div><Button type="button" variant="outline" className="add-variant-button" disabled={editor.variants.length>=100} onClick={()=>patch({variants:[...editor.variants,{id:crypto.randomUUID(),label:'',strength:'',available:true}]})}><Plus size={16}/>Add variant</Button></div>
      <div className="variant-card-grid">{editor.variants.map((v,i)=><div className={'variant-card '+(!v.available?'variant-unavailable':'')} key={v.id}>
       <div className="variant-card-heading"><span className="variant-index">Variant {String(i+1).padStart(2,'0')}</span><div className="variant-card-actions"><label className={'availability-control '+(v.available?'is-available':'')}><Switch aria-label={`${v.label||'Variant '+(i+1)} in stock`} checked={v.available} onCheckedChange={available=>patch({variants:editor.variants.map((w,j)=>j===i?{...w,available}:w)})}/><span>{v.available?'In stock':'Out of stock'}</span></label><Button aria-label={`Remove variant ${i+1}`} type="button" size="icon" variant="ghost" disabled={editor.variants.length===1} onClick={()=>patch({variants:editor.variants.filter((_,j)=>j!==i)})}><Trash2 size={15}/></Button></div></div>
       <div className="variant-card-fields"><label className="field">{editor.category==='Machines'?'Color':editor.category.includes('Coils')?'Option':'Flavor / option'}<input aria-label={`Variant ${i+1} name`} required maxLength={120} placeholder={editor.category==='Machines'?'e.g. Black':'Enter variant name'} value={v.label} onChange={e=>patch({variants:editor.variants.map((w,j)=>j===i?{...w,label:e.target.value}:w)})}/></label><label className="field">{editor.category==='Nicotine pouches'?'Strength':'Specification'}<input aria-label={`Variant ${i+1} strength or specification`} maxLength={30} placeholder={editor.category==='Nicotine pouches'?'e.g. 6mg':'Optional'} value={v.strength} onChange={e=>patch({variants:editor.variants.map((w,j)=>j===i?{...w,strength:e.target.value}:w)})}/></label></div>
      </div>)}</div><p className="variant-footnote"><ShieldCheck size={15}/>Availability applies only to this product.</p>
     </section>
     {editorError&&<p className="error" role="alert">{editorError}</p>}
    </div>
    <div className="editor-footer shrink-0"><div className="editor-save-status">{editor.id?<Button type="button" variant="ghost" className="text-destructive" onClick={()=>setRemoving(editor)} disabled={busy}><Trash2 size={16}/><span className="delete-label">Delete product</span></Button>:<><span className={'save-state-dot '+(dirty?'has-changes':'')}/><span>{dirty?'Unsaved changes':'New product'}</span></>}</div><div className="editor-footer-actions"><Button type="button" variant="outline" disabled={busy||uploading} onClick={()=>dirty?setDiscard(true):setEditor(null)}>Cancel</Button><Button className="save-product-button" disabled={busy||uploading}>{busy?<RefreshCw size={17} className="animate-spin"/>:<Check size={17}/>} {busy?'Saving…':'Save product'}</Button></div></div>
   </form>}
  </SheetContent>
 </Sheet>
 <AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard unsaved changes?</AlertDialogTitle><AlertDialogDescription>Your last saved product will remain unchanged.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={()=>{setEditor(null);setDirty(false)}}>Discard changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!removing} onOpenChange={open=>!open&&setRemoving(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {removing?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the product and its variants from inventory. A snapshot remains in the history export.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} variant="destructive" onClick={async e=>{e.preventDefault();setBusy(true);try{await api('delete',{id:removing!.id,revision:removing!.revision});setProducts(ps=>ps.filter(p=>p.id!==removing!.id));setRemoving(null);setEditor(null);setDirty(false);toast.success('Product deleted')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}>Delete product</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Admin settings</DialogTitle><DialogDescription>Update your credentials or export your inventory history.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();setSettingsError('');setBusy(true);try{await api('credentials',{username:newUsername,password:newPassword,currentPassword});setCurrentPassword('');setNewPassword('');setStatus({...status,username:newUsername});toast.success('Credentials updated. Other admin sessions were signed out.')}catch(e){setSettingsError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Username<input required minLength={3} maxLength={40} value={newUsername} onChange={e=>setNewUsername(e.target.value)}/></label><Password label="Current password" value={currentPassword} onChange={setCurrentPassword}/><Password label="New password (12+ characters)" value={newPassword} onChange={setNewPassword} autoComplete="new-password"/>{settingsError&&<p className="error" role="alert">{settingsError}</p>}<Button disabled={busy}>Update credentials</Button></form><div className="border-t pt-5 mt-2"><h3 className="font-semibold mb-2">Inventory backup</h3><p className="quiet mb-4">Export current products and up to 1,000 recent change snapshots. Image files remain in protected storage.</p><Button variant="outline" onClick={async()=>{try{const r=await fetch('/api/inventory?view=backup');const j:any=await r.json();if(!r.ok)throw Error(j.error);const u=URL.createObjectURL(new Blob([JSON.stringify(j,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='huqa-inventory-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);toast.success('Backup exported')}catch(e){toast.error((e as Error).message)}}}><Download size={16}/>Export inventory</Button></div></DialogContent></Dialog>
 </SidebarProvider>
}
