<div class="receipt-toolbar no-print"><a class="back-link" href="/merchant/orders/<?= e($order['reference']) ?>">← Back to order</a><button class="button primary" type="button" onclick="window.print()">Print receipt</button></div>
<article class="receipt">
<header class="receipt-head"><div><?php if($store['logo_path']):?><img class="receipt-logo" src="<?= e($store['logo_path']) ?>" alt=""><?php endif ?><strong class="receipt-store"><?= e($store['name']) ?></strong><?php if($store['address_text']):?><p><?= nl2br(e($store['address_text'])) ?></p><?php endif ?><?php if($store['contact_email']):?><p><?= e($store['contact_email']) ?></p><?php endif ?><p><?= e($store['whatsapp_number']) ?></p></div>
<div class="receipt-meta"><h1>Receipt</h1><p><strong><?= e($order['reference']) ?></strong></p><p><?= e(gmdate('M j, Y H:i',strtotime($order['placed_at']))) ?> UTC</p><p><?= e(ucfirst(strtolower($order['status']))) ?></p></div></header>

<section class="receipt-parties"><div><span>Bill to</span><strong><?= e($order['customer_name']) ?></strong><p><?= e($order['customer_phone']) ?></p><p><?= nl2br(e($order['delivery_address'])) ?></p></div></section>

<table class="receipt-table"><thead><tr><th>Item</th><th>Qty</th><th>Unit price</th><th>Line total</th></tr></thead><tbody><?php foreach($order['items']as$item):?><tr><td><strong><?= e($item['product_name']) ?></strong><?php if($item['variant_label']):?><br><small><?= e($item['variant_label']) ?></small><?php endif ?><?php if($item['sku_snapshot']):?><br><small>SKU <?= e($item['sku_snapshot']) ?></small><?php endif ?></td><td><?= e($item['quantity']) ?></td><td><?= e($order['currency_code']) ?> <?= e($item['unit_price']) ?></td><td><?= e($order['currency_code']) ?> <?= e($item['line_total']) ?></td></tr><?php endforeach ?></tbody></table>

<section class="receipt-totals"><?php if((float)$order['discount_amount']>0||(float)($order['offer_discount_amount']??0)>0||$order['free_delivery']):?><div><span>Subtotal</span><strong><?= e($order['currency_code']) ?> <?= e($order['subtotal']) ?></strong></div><?php if((float)($order['offer_discount_amount']??0)>0):?><div><span>Offer<?= $order['offer_snapshot']?' ('.e($order['offer_snapshot']).')':'' ?></span><strong>−<?= e($order['currency_code']) ?> <?= e($order['offer_discount_amount']) ?></strong></div><?php endif ?><?php if((float)$order['discount_amount']>0):?><div><span>Discount<?= $order['discount_code_snapshot']?' ('.e($order['discount_code_snapshot']).')':'' ?></span><strong>−<?= e($order['currency_code']) ?> <?= e($order['discount_amount']) ?></strong></div><?php endif ?><?php if($order['free_delivery']):?><div><span>Delivery</span><strong>Free delivery code applied</strong></div><?php endif ?><?php endif ?><div class="receipt-grand-total"><span>Total</span><strong><?= e($order['currency_code']) ?> <?= e($order['total']) ?></strong></div></section>

<?php if($order['notes']):?><section class="receipt-notes"><span>Notes</span><p><?= nl2br(e($order['notes'])) ?></p></section><?php endif ?>
<footer class="receipt-foot"><p>Thank you for your order.</p></footer>
</article>
