<?php
namespace App\Controllers;

use App\Core\{Request,Response,Session,View};
use App\Repositories\{AuditLogRepository,CategoryRepository};
use App\Services\{PlanAccessService,TenantContext};
use App\Services\ImageUploadService;
use App\Support\Slug;

final class CategoryController
{
    public function index(Request $request):void{$store=(new TenantContext)->store();View::render('merchant/categories/index',['title'=>'Categories','store'=>$store,'categories'=>(new CategoryRepository)->all((int)$store['id'])],'merchant');}
    public function create(Request $request):void{$store=(new TenantContext)->store();if((new PlanAccessService)->remaining((int)$store['id'],'categories')===0){Session::flash('error','Your category limit has been reached. Upgrade your plan or remove a category.');Response::redirect('/merchant/subscription');}View::render('merchant/categories/form',['title'=>'Add category','store'=>$store,'category'=>null],'merchant');}
    public function store(Request $request):void{$store=(new TenantContext)->store();$data=$this->validate($request);if(!$data)return;try{$id=(new CategoryRepository)->create((int)$store['id'],$data);}catch(\DomainException$e){Session::flash('error',$e->getMessage());Response::redirect('/merchant/subscription',303);}catch(\PDOException $e){if((string)$e->getCode()==='23000')$this->fail('/categories/create','A category with that address already exists.',$request);throw$e;}(new AuditLogRepository)->record((int)\App\Core\Auth::id(),'category.created','category',$id,['store_id'=>$store['id']]);try{$this->saveImage($request,$store,$id,null);}catch(\DomainException$e){Session::flash('error','Category created, but its image was rejected: '.$e->getMessage());Response::redirect("/categories/{$id}/edit");}Session::flash('success','Category created.');Response::redirect('/categories');}
    public function edit(Request $request):void{$store=(new TenantContext)->store();$category=(new CategoryRepository)->find((int)$store['id'],(int)$request->route('id'));if(!$category)Response::abort(404);View::render('merchant/categories/form',['title'=>'Edit category','store'=>$store,'category'=>$category],'merchant');}
    public function update(Request $request):void{$store=(new TenantContext)->store();$id=(int)$request->route('id');$repo=new CategoryRepository;$category=$repo->find((int)$store['id'],$id);if(!$category)Response::abort(404);$data=$this->validate($request);if(!$data)return;try{$ok=$repo->update((int)$store['id'],$id,$data);}catch(\PDOException $e){if((string)$e->getCode()==='23000')$this->fail("/categories/{$id}/edit",'A category with that address already exists.',$request);throw$e;}if(!$ok)Response::abort(404);(new AuditLogRepository)->record((int)\App\Core\Auth::id(),'category.updated','category',$id,['store_id'=>$store['id']]);try{$this->saveImage($request,$store,$id,$category['image_path']);}catch(\DomainException$e){Session::flash('error','Category saved, but its image was rejected: '.$e->getMessage());Response::redirect("/categories/{$id}/edit");}Session::flash('success','Category updated.');Response::redirect('/categories');}
    public function toggle(Request $request):void{$store=(new TenantContext)->store();$id=(int)$request->route('id');if(!(new CategoryRepository)->toggle((int)$store['id'],$id))Response::abort(404);(new AuditLogRepository)->record((int)\App\Core\Auth::id(),'category.visibility_changed','category',$id,['store_id'=>$store['id']]);Session::flash('success','Category visibility updated.');Response::redirect('/categories');}
    public function move(Request $request):void{$store=(new TenantContext)->store();$direction=(string)$request->input('direction');if(!in_array($direction,['up','down'],true))Response::abort(400);if(!(new CategoryRepository)->move((int)$store['id'],(int)$request->route('id'),$direction))Response::abort(404);Response::redirect('/categories');}
    public function delete(Request $request):void{$store=(new TenantContext)->store();$id=(int)$request->route('id');$repo=new CategoryRepository;$category=$repo->find((int)$store['id'],$id);$result=$repo->deleteSafe((int)$store['id'],$id);if($result==='missing')Response::abort(404);if($result==='in_use'){Session::flash('error','Move or delete this category’s products before deleting the category.');Response::redirect('/categories');}(new ImageUploadService)->removePath($category['image_path']??null);(new AuditLogRepository)->record((int)\App\Core\Auth::id(),'category.deleted','category',$id,['store_id'=>$store['id']]);Session::flash('success','Category deleted.');Response::redirect('/categories');}

    private function validate(Request $request):?array{$name=trim((string)$request->input('name'));$slug=Slug::make((string)($request->input('slug')?:$name));$description=trim((string)$request->input('description'));$status=(string)$request->input('status');$errors=[];if(mb_strlen($name)<2||mb_strlen($name)>100)$errors[]='Category name must be 2–100 characters.';if($slug===''||mb_strlen($slug)>100)$errors[]='Enter a valid category address.';if(mb_strlen($description)>500)$errors[]='Description is too long.';if(!in_array($status,['ACTIVE','INACTIVE'],true))$errors[]='Choose a valid status.';if($errors){$id=$request->route('id');$this->fail($id?"/categories/{$id}/edit":'/categories/create',implode(' ',$errors),$request);}return['name'=>$name,'slug'=>$slug,'description'=>$description===''?null:$description,'status'=>$status];}
    private function fail(string $path,string $message,Request $request):never{Session::put('_old',array_diff_key($request->all(),['_token'=>true]));Session::flash('error',$message);Response::redirect($path);}
    private function saveImage(Request$request,array$store,int$id,?string$old):void{$repo=new CategoryRepository;$upload=new ImageUploadService;if($request->input('remove_image')){$repo->setImage((int)$store['id'],$id,null);$upload->removePath($old);$old=null;}$file=$request->file('image');if($file&&(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$path=$upload->uploadCategory((int)$store['id'],$file);$repo->setImage((int)$store['id'],$id,$path);$upload->removePath($old);}}
}
