<?php
namespace App\Controllers;

use App\Core\{Auth,Request,Response,Session,View};
use App\Repositories\{AuditLogRepository,CategoryRepository,ImageRepository,ProductRepository};
use App\Services\{ImageUploadService,PlanAccessService,TenantContext};
use App\Support\Slug;

final class ProductController
{
    public function index(Request $request):void{$store=(new TenantContext)->store();$filters=['q'=>mb_substr(trim((string)$request->query('q')),0,120),'category_id'=>(int)$request->query('category_id'),'status'=>strtoupper((string)$request->query('status')),'availability'=>strtoupper((string)$request->query('availability')),'sort'=>(string)$request->query('sort','newest'),'page'=>max(1,(int)$request->query('page',1))];$allowedStatus=['','DRAFT','ACTIVE','ARCHIVED'];$allowedAvailability=['','AVAILABLE','UNAVAILABLE'];if(!in_array($filters['status'],$allowedStatus,true))$filters['status']='';if(!in_array($filters['availability'],$allowedAvailability,true))$filters['availability']='';$repo=new ProductRepository;$result=$repo->search((int)$store['id'],$filters);if($filters['page']>$result['pages']&&$result['total']>0)Response::redirect('/products');View::render('merchant/products/index',['title'=>'Products','store'=>$store,'products'=>$result['items'],'pagination'=>$result,'categories'=>(new CategoryRepository)->all((int)$store['id']),'filters'=>$filters],'merchant');}
    public function create(Request $request):void{$store=(new TenantContext)->store();if((new PlanAccessService)->remaining((int)$store['id'],'products')===0){Session::flash('error','Your product limit has been reached. Upgrade your plan or remove a product.');Response::redirect('/merchant/subscription');}$this->form($store,null,'Add product');}
    public function edit(Request $request):void{$store=(new TenantContext)->store();$product=(new ProductRepository)->find((int)$store['id'],(int)$request->route('id'));if(!$product)Response::abort(404);$this->form($store,$product,'Edit product');}
    private function form(array $store,?array $product,string $title):void{View::render('merchant/products/form',['title'=>$title,'store'=>$store,'product'=>$product,'categories'=>(new CategoryRepository)->all((int)$store['id'],true)],'merchant');}

    public function store(Request $request):void{$store=(new TenantContext)->store();[$data,$options]=$this->validated($request,(int)$store['id']);try{$id=(new ProductRepository)->create((int)$store['id'],$data,$options);}catch(\DomainException$e){Session::flash('error',$e->getMessage());Response::redirect('/merchant/subscription',303);}catch(\PDOException $e){if((string)$e->getCode()==='23000')$this->fail('/products/create','The product address or SKU already exists.',$request);throw$e;}(new AuditLogRepository)->record((int)Auth::id(),'product.created','product',$id,['store_id'=>$store['id']]);try{(new ImageUploadService)->uploadMany((int)$store['id'],$id,$request->file('images'));}catch(\DomainException $e){Session::flash('error','Product created, but images were rejected: '.$e->getMessage());Response::redirect("/products/{$id}/edit");}if($options){Session::flash('success','Product created. Each variant below (every color, size, or other combination) is tracked separately — set its own SKU, price, stock, and availability.');Response::redirect("/products/{$id}/edit");}Session::flash('success','Product created.');Response::redirect('/products');}
    public function update(Request $request):void{$store=(new TenantContext)->store();$id=(int)$request->route('id');[$data,$options]=$this->validated($request,(int)$store['id'],$id);$variantInputs=is_array($request->input('variants'))?$request->input('variants'):[];try{$ok=(new ProductRepository)->update((int)$store['id'],$id,$data,$options,$variantInputs);}catch(\PDOException $e){if((string)$e->getCode()==='23000')$this->fail("/products/{$id}/edit",'The product address, product SKU, or variant SKU already exists.',$request);throw$e;}if(!$ok)Response::abort(404);(new AuditLogRepository)->record((int)Auth::id(),'product.updated','product',$id,['store_id'=>$store['id']]);try{(new ImageUploadService)->uploadMany((int)$store['id'],$id,$request->file('images'));}catch(\DomainException $e){Session::flash('error','Product saved, but images were rejected: '.$e->getMessage());Response::redirect("/products/{$id}/edit");}Session::flash('success','Product updated.');Response::redirect('/products');}
    public function duplicate(Request $request):void{$store=(new TenantContext)->store();try{$id=(new ProductRepository)->duplicate((int)$store['id'],(int)$request->route('id'));}catch(\DomainException$e){Session::flash('error',$e->getMessage());Response::redirect('/merchant/subscription',303);}if(!$id)Response::abort(404);(new AuditLogRepository)->record((int)Auth::id(),'product.duplicated','product',$id,['store_id'=>$store['id']]);Session::flash('success','Product duplicated as a draft. Images were not copied.');Response::redirect("/products/{$id}/edit");}
    public function archive(Request $request):void{$store=(new TenantContext)->store();$id=(int)$request->route('id');if(!(new ProductRepository)->archive((int)$store['id'],$id))Response::abort(404);(new AuditLogRepository)->record((int)Auth::id(),'product.archived','product',$id,['store_id'=>$store['id']]);Session::flash('success','Product archived.');Response::redirect('/products');}
    public function delete(Request $request):void{$store=(new TenantContext)->store();$id=(int)$request->route('id');if(!(new ProductRepository)->delete((int)$store['id'],$id))Response::abort(404);(new AuditLogRepository)->record((int)Auth::id(),'product.deleted','product',$id,['store_id'=>$store['id']]);Session::flash('success','Product deleted.');Response::redirect('/products');}
    public function deleteImage(Request $request):void{$store=(new TenantContext)->store();$productId=(int)$request->route('id');$imageId=(int)$request->route('imageId');if(!(new ProductRepository)->find((int)$store['id'],$productId))Response::abort(404);$image=(new ImageRepository)->delete((int)$store['id'],$productId,$imageId);if(!$image)Response::abort(404);(new ImageUploadService)->removeFiles($image);(new AuditLogRepository)->record((int)Auth::id(),'product.image_deleted','product',$productId,['store_id'=>$store['id'],'image_id'=>$imageId]);Session::flash('success','Image removed.');Response::redirect("/products/{$productId}/edit");}

    private function validated(Request $request,int $storeId,?int $id=null):array
    {
        $name=trim((string)$request->input('name'));$slug=Slug::make((string)($request->input('slug')?:$name));$sku=trim((string)$request->input('sku'));$description=trim((string)$request->input('description'));$price=trim((string)$request->input('price'));$compare=trim((string)$request->input('compare_price'));$category=(int)$request->input('category_id');$availability=(string)$request->input('availability');$status=(string)$request->input('status');$errors=[];
        if(mb_strlen($name)<2||mb_strlen($name)>160)$errors[]='Product name must be 2–160 characters.';if($slug===''||mb_strlen($slug)>180)$errors[]='Enter a valid product address.';if($sku!==''&&mb_strlen($sku)>100)$errors[]='SKU is too long.';if(mb_strlen($description)>10000)$errors[]='Description is too long.';if(!$this->money($price))$errors[]='Enter a valid price with at most two decimals.';if($compare!==''&&!$this->money($compare))$errors[]='Compare price is invalid.';if($compare!==''&&$this->minor($compare)<=$this->minor($price))$errors[]='Compare price must be greater than the selling price.';if(!in_array($availability,['AVAILABLE','UNAVAILABLE'],true))$errors[]='Choose valid availability.';if(!in_array($status,['DRAFT','ACTIVE','ARCHIVED'],true))$errors[]='Choose a valid product status.';
        if($category&&!(new CategoryRepository)->find($storeId,$category))$errors[]='Choose a category from this store.';$options=$this->options($request,$errors);$variantInputs=is_array($request->input('variants'))?$request->input('variants'):[];foreach($variantInputs as$v){$adjust=(string)($v['price_adjustment']??'0');if(!preg_match('/^-?\d{1,10}(?:\.\d{1,2})?$/',$adjust))$errors[]='A variant price adjustment is invalid.';elseif($this->minor($price)+$this->minorSigned($adjust)<0)$errors[]='A variant adjustment cannot make the final price negative.';$variantSku=trim((string)($v['sku']??''));if(mb_strlen($variantSku)>100)$errors[]='Variant SKU is too long.';$stock=(string)($v['stock_quantity']??'');if($stock!==''&&(!ctype_digit($stock)||(int)$stock>4294967295))$errors[]='Variant stock must be a valid whole non-negative number.';}
        if($errors)$this->fail($id?"/products/{$id}/edit":'/products/create',implode(' ',array_unique($errors)),$request);
        return[['category_id'=>$category?:null,'name'=>$name,'slug'=>$slug,'sku'=>$sku===''?null:$sku,'description'=>$description===''?null:$description,'price'=>$price,'compare_price'=>$compare===''?null:$compare,'availability'=>$availability,'is_featured'=>$request->input('is_featured')?1:0,'status'=>$status],$options];
    }
    private function options(Request $request,array &$errors):array{$raw=$request->input('options',[]);if(!is_array($raw))return[];if(count($raw)>3)$errors[]='A product can have at most three option groups.';$out=[];$optionNames=[];foreach(array_slice($raw,0,3)as$option){$name=trim((string)($option['name']??''));$rawValues=array_values(array_filter(array_map('trim',explode(',',(string)($option['values']??''))),static fn($value)=>$value!==''));$values=[];$seen=[];foreach($rawValues as$value){$key=mb_strtolower($value);if(isset($seen[$key])){$errors[]='Variant values must be unique within each option.';continue;}$seen[$key]=true;$values[]=$value;}if($name===''&&count($values)===0)continue;$nameKey=mb_strtolower($name);if(isset($optionNames[$nameKey]))$errors[]='Variant option names must be unique.';$optionNames[$nameKey]=true;if($name===''||mb_strlen($name)>80||count($values)<1)$errors[]='Each variant option needs a name and at least one comma-separated value.';foreach($values as$value)if(mb_strlen($value)>100)$errors[]='Variant values must be 100 characters or fewer.';$out[]=['name'=>$name,'values'=>$values];}$count=1;foreach($out as$option)$count*=count($option['values']);if($count>30)$errors[]='Variants are limited to 30 combinations per product.';return$out;}
    private function money(string $value):bool{return(bool)preg_match('/^\d{1,10}(?:\.\d{1,2})?$/',$value);}
    private function minor(string $value):int{[$whole,$decimal]=array_pad(explode('.',$value,2),2,'');return((int)$whole*100)+(int)str_pad(substr($decimal,0,2),2,'0');}
    private function minorSigned(string $value):int{$negative=str_starts_with($value,'-');$amount=$this->minor(ltrim($value,'-'));return$negative?-$amount:$amount;}
    private function fail(string $path,string $message,Request $request):never{Session::put('_old',array_diff_key($request->all(),['_token'=>true]));Session::flash('error',$message);Response::redirect($path);}
}
