<?php
namespace App\Controllers;

use App\Core\{Auth,Request,Response,Session,View};
use App\Repositories\{AuditLogRepository,StoreRepository};
use App\Services\{ImageUploadService,TenantContext};
use App\Support\Validation;

final class StoreDesignController
{
    public function form(Request$request):void{$store=(new TenantContext)->store();View::render('merchant/design',['title'=>'Store Design','store'=>$store,'app'=>config('app'),'storeUrl'=>store_absolute_url($store)],'merchant');}

    public function update(Request$request):void
    {
        $store=(new TenantContext)->store();$app=config('app');$data=['name'=>trim((string)$request->input('name')),'slug'=>mb_strtolower(trim((string)$request->input('slug'))),'theme'=>mb_strtolower(trim((string)$request->input('theme'))),'accent_color'=>strtoupper(trim((string)$request->input('accent_color'))),'font_key'=>mb_strtolower(trim((string)$request->input('font_key'))),'description'=>trim((string)$request->input('description')),'contact_email'=>mb_strtolower(trim((string)$request->input('contact_email'))),'address_text'=>trim((string)$request->input('address_text')),'instagram'=>trim((string)$request->input('instagram')),'facebook'=>trim((string)$request->input('facebook')),'tiktok'=>trim((string)$request->input('tiktok'))];$errors=[];
        if(mb_strlen($data['name'])<2||mb_strlen($data['name'])>120)$errors[]='Store name must be 2–120 characters.';if(!Validation::slug($data['slug'])||mb_strlen($data['slug'])<3||mb_strlen($data['slug'])>63)$errors[]='Store address must be 3–63 lowercase letters, numbers, or single hyphens.';if(in_array($data['slug'],$app['reserved_slugs'],true))$errors[]='That store address is reserved.';if(!in_array($data['theme'],$app['themes'],true))$errors[]='Choose a valid template.';if(!isset($app['fonts'][$data['font_key']]))$errors[]='Choose an approved font.';if(!preg_match('/^#[0-9A-F]{6}$/',$data['accent_color']))$errors[]='Choose a valid accent color.';if(mb_strlen($data['description'])>500)$errors[]='Store description cannot exceed 500 characters.';if($data['contact_email']!==''&&!filter_var($data['contact_email'],FILTER_VALIDATE_EMAIL))$errors[]='Enter a valid contact email.';if(mb_strlen($data['address_text'])>500)$errors[]='Address cannot exceed 500 characters.';
        foreach(['instagram','facebook','tiktok']as$key)if($data[$key]!==''&&!$this->validUrl($data[$key]))$errors[]=ucfirst($key).' must be a complete http or https URL.';$repo=new StoreRepository;if(!$repo->slugAvailableFor((int)$store['id'],$data['slug'])&&$data['slug']!==$store['slug'])$errors[]='That store address is already in use or reserved as an old address.';if($errors)$this->fail(implode(' ',$errors),$data);
        $upload=new ImageUploadService;$logo=$request->input('remove_logo')?null:$store['logo_path'];$banner=$request->input('remove_banner')?null:$store['banner_path'];$new=[];
        try{$logoFile=$request->file('logo');if($logoFile&&(int)($logoFile['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$logo=$upload->uploadStoreAsset((int)$store['id'],'logo',$logoFile);$new[]=$logo;}$bannerFile=$request->file('banner');if($bannerFile&&(int)($bannerFile['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$banner=$upload->uploadStoreAsset((int)$store['id'],'banner',$bannerFile);$new[]=$banner;}$repo->updateDesign((int)$store['id'],['name'=>$data['name'],'slug'=>$data['slug'],'theme'=>$data['theme'],'logo_path'=>$logo,'banner_path'=>$banner,'accent_color'=>$data['accent_color'],'font_key'=>$data['font_key'],'description'=>$data['description']===''?null:$data['description'],'contact_email'=>$data['contact_email']===''?null:$data['contact_email'],'address_text'=>$data['address_text']===''?null:$data['address_text'],'social_links'=>array_filter(['instagram'=>$data['instagram'],'facebook'=>$data['facebook'],'tiktok'=>$data['tiktok']],static fn($value)=>$value!=='')]);}
        catch(\DomainException$e){foreach($new as$path)$upload->removePath($path);$this->fail($e->getMessage(),$data);}catch(\PDOException$e){foreach($new as$path)$upload->removePath($path);if((string)$e->getCode()==='23000')$this->fail('That store address is already in use or reserved as an old address.',$data);throw$e;}catch(\Throwable$e){foreach($new as$path)$upload->removePath($path);throw$e;}
        if($store['logo_path']&&$store['logo_path']!==$logo)$upload->removePath($store['logo_path']);if($store['banner_path']&&$store['banner_path']!==$banner)$upload->removePath($store['banner_path']);(new AuditLogRepository)->record((int)Auth::id(),'store.design_updated','store',(int)$store['id'],['old_slug'=>$store['slug'],'new_slug'=>$data['slug'],'theme'=>$data['theme']]);Session::flash('success','Store design and public details updated.');Response::redirect('/merchant/design');
    }
    private function validUrl(string$url):bool{if(mb_strlen($url)>255||!filter_var($url,FILTER_VALIDATE_URL))return false;$scheme=mb_strtolower((string)parse_url($url,PHP_URL_SCHEME));return in_array($scheme,['http','https'],true)&&(bool)parse_url($url,PHP_URL_HOST);}
    private function fail(string$message,array$data):never{Session::put('_old',$data);Session::flash('error',$message);Response::redirect('/merchant/design',303);}
}
