<?php
namespace App\Controllers;

use App\Core\{Request,Response,View};
use App\Repositories\{OfferRepository,StorefrontRepository};
use App\Support\Money;

final class StorefrontController
{
    public function home(Request$request):void{$repo=new StorefrontRepository;$store=$this->store($repo,(string)$request->route('storeSlug'));if($store['status']==='SUSPENDED'){$this->suspended($store);return;}$query=mb_substr(trim((string)$request->query('q')),0,100);$categorySlug=trim((string)$request->query('category'));$category=$categorySlug!==''?$repo->categoryBySlug((int)$store['id'],$categorySlug):null;if($categorySlug!==''&&!$category)Response::abort(404);$page=max(1,(int)$request->query('page',1));$catalog=$repo->catalog((int)$store['id'],$query,$category?(int)$category['id']:null,$page);if($page>$catalog['pages']&&$catalog['total']>0)Response::abort(404);$meta=['title'=>$store['seo_title']?:$store['name'],'description'=>$store['seo_description']?:($store['description']?:'Browse '.$store['name'].' and order on WhatsApp.'),'canonical'=>config('app')['url'].'/'.$store['slug'],'image'=>$store['banner_path']?:$store['logo_path'],'type'=>'website'];if($query!==''||$category||$page>1)$meta['robots']='noindex,follow';View::render('storefront/home',['title'=>$store['name'],'store'=>$store,'categories'=>$repo->categories((int)$store['id']),'featured'=>($query===''&&!$category&&$page===1)?$repo->featured((int)$store['id']):[],'catalog'=>$catalog,'query'=>$query,'selectedCategory'=>$category,'meta'=>$meta],'storefront');}
    public function product(Request$request):void{$repo=new StorefrontRepository;$productSlug=(string)$request->route('productSlug');$store=$this->store($repo,(string)$request->route('storeSlug'),'/product/'.$productSlug);if($store['status']==='SUSPENDED'){$this->suspended($store);return;}$product=$repo->product((int)$store['id'],$productSlug);if(!$product)Response::abort(404);$description=$product['description']?mb_substr(trim(preg_replace('/\s+/',' ',$product['description'])),0,200):'View '.$product['name'].' from '.$store['name'].'.';$canonical=config('app')['url'].'/'.$store['slug'].'/product/'.$product['slug'];$meta=['title'=>$product['name'].' · '.$store['name'],'description'=>$description,'canonical'=>$canonical,'image'=>$product['images'][0]['path']??$store['logo_path'],'type'=>'product','structured_data'=>$this->productStructuredData($store,$product,$canonical,$description)];View::render('storefront/product',['title'=>$product['name'],'store'=>$store,'product'=>$product,'related'=>$repo->related((int)$store['id'],(int)$product['id'],$product['category_id']?(int)$product['category_id']:null),'meta'=>$meta],'storefront');}
    public function cart(Request$request):void{$repo=new StorefrontRepository;$store=$this->store($repo,(string)$request->route('storeSlug'),'/cart');if($store['status']==='SUSPENDED'){$this->suspended($store);return;}View::render('storefront/cart',['title'=>'Your cart','store'=>$store,'meta'=>['robots'=>'noindex,nofollow','canonical'=>config('app')['url'].'/'.$store['slug'].'/cart']],'storefront');}
    public function offers(Request$request):void{$repo=new StorefrontRepository;$store=$this->store($repo,(string)$request->route('storeSlug'),'/offers');if($store['status']==='SUSPENDED'){$this->suspended($store);return;}if(!$store['offers_page_enabled'])Response::abort(404);$offers=(new OfferRepository)->activeForStore((int)$store['id']);View::render('storefront/offers',['title'=>'Offers','store'=>$store,'offers'=>$offers,'meta'=>['title'=>'Offers · '.$store['name'],'description'=>'Current deals and bundles at '.$store['name'].'.','canonical'=>config('app')['url'].'/'.$store['slug'].'/offers']],'storefront');}
    private function store(StorefrontRepository$repo,string$slug,string$suffix=''):array{$store=$repo->storeBySlug($slug);if(!$store){$target=$repo->redirectTarget($slug);if($target)Response::redirect('/'.$target.$suffix,301);Response::abort(404);}return$store;}
    private function suspended(array$store):void{http_response_code(503);View::render('storefront/suspended',['title'=>'Store unavailable','store'=>$store],'storefront');}
    private function productStructuredData(array$store,array$product,string$canonical,string$description):array
    {
        $prices=[];$available=$product['availability']==='AVAILABLE';if($product['variants']){$available=false;foreach($product['variants']as$variant){if($variant['purchasable']){$available=true;$prices[]=Money::minor((string)$variant['final_price']);}}}$price=$prices?Money::fromMinor(min($prices)):(string)$product['price'];$images=[];foreach($product['images']as$image){$path=(string)$image['path'];$images[]=str_starts_with($path,'/')?config('app')['url'].$path:$path;}
        $data=['@context'=>'https://schema.org','@type'=>'Product','name'=>$product['name'],'description'=>$description,'url'=>$canonical,'offers'=>['@type'=>'Offer','url'=>$canonical,'priceCurrency'=>$store['currency_code'],'price'=>$price,'availability'=>$available?'https://schema.org/InStock':'https://schema.org/OutOfStock']];if($product['sku'])$data['sku']=$product['sku'];if($images)$data['image']=$images;return$data;
    }
}
