ALTER TABLE order_status_history
  ADD COLUMN reason_code ENUM('HIGH_DELIVERY_FEE','CUSTOMER_UNREACHABLE','CHANGED_MIND','OUT_OF_STOCK','DUPLICATE_ORDER','OTHER') NULL AFTER status,
  ADD COLUMN reason_note VARCHAR(300) NULL AFTER reason_code;
