<?php $editing=(bool)$code;$old=App\Core\Session::get('_old',[]);$value=static fn($key,$default='')=>$old[$key]??($code[$key]??$default);$toLocal=static fn(?string$v):string=>$v?gmdate('Y-m-d\TH:i',strtotime($v)):''; ?>
<section class="page-head"><div><a class="back-link" href="/merchant/discounts">← Discount codes</a><h1><?= $editing?'Edit discount code':'Add discount code' ?></h1><p class="muted">Every rule here is enforced server-side at checkout — dates, limits, and scope cannot be bypassed from the browser.</p></div></section>
<form method="post" action="<?= $editing?'/merchant/discounts/'.e($code['id']):'/merchant/discounts' ?>" class="editor-layout" data-discount-form>
<?= csrf_field() ?>
<div class="editor-sections">
<section class="panel form-section"><div class="section-heading"><span>01</span><div><h2>Code</h2><p>What the customer types at checkout.</p></div></div><div class="form-grid compact-grid"><label class="full">Code<input name="code" value="<?= e($value('code')) ?>" maxlength="40" placeholder="SAVE10" style="text-transform:uppercase" required></label><label>Status<select name="status"><option value="ACTIVE" <?= $value('status','ACTIVE')==='ACTIVE'?'selected':'' ?>>Active</option><option value="INACTIVE" <?= $value('status')==='INACTIVE'?'selected':'' ?>>Inactive</option></select></label></div></section>

<section class="panel form-section"><div class="section-heading"><span>02</span><div><h2>Discount type</h2><p>Choose one mechanic per code.</p></div></div><div class="form-grid compact-grid"><label class="full">Type<select name="type" data-discount-type><option value="PERCENT_ORDER" <?= $value('type','PERCENT_ORDER')==='PERCENT_ORDER'?'selected':'' ?>>Percentage off entire order</option><option value="FIXED_ORDER" <?= $value('type')==='FIXED_ORDER'?'selected':'' ?>>Fixed amount off entire order</option><option value="PERCENT_PRODUCT" <?= $value('type')==='PERCENT_PRODUCT'?'selected':'' ?>>Percentage off a specific product</option><option value="PERCENT_CATEGORY" <?= $value('type')==='PERCENT_CATEGORY'?'selected':'' ?>>Percentage off a specific category</option><option value="FREE_DELIVERY" <?= $value('type')==='FREE_DELIVERY'?'selected':'' ?>>Free delivery (flag only — you honor it manually)</option></select></label>
<label class="full" data-discount-field="value">Value<input name="value" value="<?= e($value('value')) ?>" inputmode="decimal" placeholder="e.g. 10"><small data-discount-value-hint>Percentage (0–100) or a fixed amount in your store currency, depending on the type above.</small></label>
<label class="full" data-discount-field="scope_product_id"><?php $products=$products??[];?>Product<select name="scope_product_id"><option value="0">Choose a product…</option><?php foreach($products as$p):?><option value="<?= e($p['id']) ?>" <?= (int)$value('scope_product_id')===(int)$p['id']?'selected':'' ?>><?= e($p['name']) ?></option><?php endforeach ?></select></label>
<label class="full" data-discount-field="scope_category_id"><?php $categories=$categories??[];?>Category<select name="scope_category_id"><option value="0">Choose a category…</option><?php foreach($categories as$c):?><option value="<?= e($c['id']) ?>" <?= (int)$value('scope_category_id')===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach ?></select></label>
</div></section>

<section class="panel form-section"><div class="section-heading"><span>03</span><div><h2>Limits</h2><p>All optional — leave blank for no limit.</p></div></div><div class="form-grid compact-grid"><label>Minimum order amount <span class="optional">Optional</span><input name="min_order_amount" value="<?= e($value('min_order_amount')) ?>" inputmode="decimal" placeholder="e.g. 25.00"></label><label>Total use limit <span class="optional">Optional</span><input name="usage_limit" value="<?= e($value('usage_limit')) ?>" inputmode="numeric" placeholder="e.g. 100"></label><label>Uses per customer <span class="optional">Optional</span><input name="usage_limit_per_customer" value="<?= e($value('usage_limit_per_customer')) ?>" inputmode="numeric" placeholder="e.g. 1"></label></div></section>

<section class="panel form-section"><div class="section-heading"><span>04</span><div><h2>Active window</h2><p>Leave blank to run indefinitely — useful for holiday offers with a fixed window.</p></div></div><div class="form-grid compact-grid"><label>Starts <span class="optional">Optional</span><input type="datetime-local" name="starts_at" value="<?= e($toLocal($value('starts_at')?:null)) ?>"></label><label>Ends <span class="optional">Optional</span><input type="datetime-local" name="ends_at" value="<?= e($toLocal($value('ends_at')?:null)) ?>"></label></div></section>
</div>
<aside class="editor-actions panel"><strong><?= $editing?'Save discount code':'Create discount code' ?></strong><p>Changes are validated server-side before they are saved.</p><button class="button primary" type="submit"><?= $editing?'Save changes':'Create discount code' ?></button><a class="button secondary" href="/merchant/discounts">Cancel</a></aside>
</form>
