<?php
declare(strict_types=1);
require_once __DIR__ . '/../inc/bootstrap.php';
if(!is_admin()){header('Location: login.php');exit;}
$siteSettings=settings();
?><!doctype html><html lang="en" data-motion="full"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b0b0d"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%23ff0000'/%3E%3Crect x='23' y='14' width='18' height='36' rx='4' fill='%23fff'/%3E%3C/svg%3E"><title>DR PHONE Admin Dashboard</title>
<link rel="preload" href="../assets/fonts/outfit-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="../assets/admin.css?v=15">
<script nonce="<?=htmlspecialchars(CSP_NONCE)?>">
/* Motion tier decided before first paint, same mechanism as the storefront. */
(function(){var r=document.documentElement,m=window.matchMedia;
if(m&&m('(prefers-reduced-motion: reduce)').matches){r.setAttribute('data-motion','off');return}
var cores=navigator.hardwareConcurrency||8,mem=navigator.deviceMemory||8;
if(cores<=2||mem<=2)r.setAttribute('data-motion','lite')})();
</script>
</head><body data-tab="overview"><div class="bg-mesh" aria-hidden="true"></div><header class="admin-header"><div class="admin-brand"><img class="admin-brand-logo" src="../dr-phone-logo.png" alt="Dr. phone"><h1>Catalog dashboard</h1></div><nav><button id="open-operations" class="header-button">Operations</button><button id="open-settings" class="header-button">Account & store</button><a href="../" target="_blank">View catalog</a><a href="logout.php">Log out</a></nav></header><nav class="tab-bar" role="tablist" aria-label="Dashboard sections">
<button type="button" class="tab active" data-tab-button="overview" role="tab" aria-selected="true">Overview</button>
<button type="button" class="tab" data-tab-button="products" role="tab" aria-selected="false">Products</button>
<button type="button" class="tab" data-tab-button="sales" role="tab" aria-selected="false">Sales</button>
</nav>
<main class="admin-main"><section id="admin-overview" class="admin-overview" aria-live="polite"></section><section id="admin-sales" class="admin-sales" aria-live="polite"></section><section class="toolbar"><div><strong id="summary">Loading…</strong><span>Manage products, stock, pricing, visibility and wholesale tools</span></div><div class="toolbar-actions"><input id="admin-search" type="search" placeholder="Search products"><button id="export-csv" class="secondary">Export Excel CSV</button><button id="print-prices" class="secondary">Print price list</button><button id="add-category" class="secondary">Add category</button><button id="add-product">Add product</button></div></section><section id="bulk-bar" class="bulk-bar" hidden><strong><span id="selected-count">0</span> selected</strong><select id="bulk-stock"><option value="">Stock unchanged</option><option value="in-stock">In stock</option><option value="low-stock">Low stock</option><option value="out-of-stock">Out of stock</option></select><select id="bulk-visibility"><option value="">Visibility unchanged</option><option value="published">Published</option><option value="draft">Draft</option><option value="hidden">Hidden</option></select><select id="bulk-category"><option value="">Category unchanged</option></select><button id="apply-bulk">Apply changes</button><button id="clear-selection" class="secondary">Clear</button></section><div id="notice" role="status"></div><section id="admin-content" class="admin-content"></section></main>
<dialog id="product-dialog"><form id="product-form" method="dialog" enctype="multipart/form-data"><div class="dialog-head"><h2 id="product-title">Add product</h2><button type="button" class="icon-button" data-close>×</button></div><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="save_product"><input type="hidden" name="id"><div class="form-grid"><label>Category<select name="category" required></select></label><label>Product name<input name="name" required maxlength="250"></label><label>Brand<input name="brand" maxlength="100"></label><label>Stock status<select name="stock"><option value="in-stock">In stock</option><option value="low-stock">Low stock</option><option value="out-of-stock">Out of stock</option></select></label><label>Stock quantity<input name="stock_quantity" type="number" min="0" step="1"><small>Optional exact quantity.</small></label><label>Visibility<select name="visibility"><option value="published">Published</option><option value="draft">Draft</option><option value="hidden">Hidden</option></select></label><label>Single price in USD<input name="price" type="number" min="0" step="0.01"><small>Use only for one price.</small></label><label>Type/details<input name="type" maxlength="300"></label><label class="full">Quantity price tiers<textarea name="tiers" rows="4" placeholder="10 | 9.50&#10;50 | 8.75"></textarea><small>Minimum quantity | unit price. The cart applies the best tier automatically.</small></label><input type="hidden" name="options"><input type="hidden" name="colors"><input type="hidden" name="flavors"><input type="hidden" name="variant_stock"><label class="full">Primary product image<input name="image" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG or WEBP; maximum 5 MB.</small></label><label class="full">Additional gallery images<input name="images[]" type="file" accept="image/jpeg,image/png,image/webp" multiple><small>Select up to 5 additional images per save.</small></label></div><div class="dialog-actions"><button type="button" class="secondary" data-close>Cancel</button><button type="submit">Save product</button></div></form></dialog>
<dialog id="category-dialog"><form id="category-form" method="dialog"><div class="dialog-head"><h2>Add category</h2><button type="button" class="icon-button" data-close>×</button></div><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="add_category"><label>Category name<input name="name" required maxlength="100"></label><div class="dialog-actions"><button type="button" class="secondary" data-close>Cancel</button><button type="submit">Add category</button></div></form></dialog>
<dialog id="settings-dialog"><form id="settings-form" method="dialog"><div class="dialog-head"><h2>Account & store settings</h2><button type="button" class="icon-button" data-close>×</button></div><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="save_settings"><div class="form-grid"><label>Admin username<input name="admin_username" required maxlength="64" autocomplete="username"></label><label>Current admin password<input name="current_password" type="password" required autocomplete="current-password"></label><label>New admin password<input name="new_password" type="password" minlength="12" autocomplete="new-password"><small>Leave blank to keep it.</small></label><label>Confirm admin password<input name="confirm_password" type="password" minlength="12" autocomplete="new-password"></label><label>New customer passcode<input name="new_customer_passcode" type="password" minlength="8" autocomplete="new-password"><small>Leave blank to keep it. Minimum 8 characters.</small></label><label>Confirm customer passcode<input name="confirm_customer_passcode" type="password" minlength="8" autocomplete="new-password"></label><label class="full two-factor-setting"><span><input name="two_factor_enabled" type="checkbox"> Require a 6-digit authenticator code for dashboard login</span><small id="two-factor-help">Enable, save, then copy the setup key into Google Authenticator, Microsoft Authenticator or 1Password.</small><code id="two-factor-secret"></code></label><label>Phone number<input name="phone" required></label><label>Location label<input name="location" required></label><label class="full">Google Maps link<input name="map_url" type="url" required></label><label>Currency<input name="currency" maxlength="3" value="USD" pattern="[A-Za-z]{3}" title="Three-letter currency code, for example USD or EUR"></label><label>Minimum order<input name="minimum_order" type="number" min="0" step="0.01"></label><label class="full">Payment terms<textarea name="payment_terms" rows="3"></textarea></label><label class="full">Delivery terms<textarea name="delivery_terms" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="secondary" data-close>Cancel</button><button type="submit">Save settings</button></div></form></dialog>
<dialog id="operations-dialog"><div class="operations-panel"><div class="dialog-head"><h2>Catalog operations</h2><button type="button" class="icon-button" data-close>×</button></div><div class="operations-grid"><section><h3>Spreadsheet import</h3><p>Import products from an Excel-compatible CSV file.</p><form id="import-form" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="import_csv"><input name="csv" type="file" accept=".csv,text/csv" required><button type="submit">Import CSV</button></form></section><section><h3>Image quality audit</h3><p id="audit-summary">Checking images…</p><div id="audit-list" class="tool-list"></div></section><section><h3>Automatic backups</h3><p>Every catalog change creates a recoverable copy.</p><div id="backup-list" class="tool-list"></div></section><section><h3>Activity log</h3><div id="activity-list" class="tool-list"></div></section><section class="orders-section"><h3>Order log</h3><p id="orders-summary">Loading…</p><div class="orders-toolbar"><input id="orders-search" type="search" placeholder="Search by reference (DR-…)" aria-label="Search orders by reference"><button type="button" id="orders-export" class="secondary">Export CSV</button><button type="button" id="orders-clear" class="secondary">Clear all</button></div><div id="orders-list" class="tool-list"></div><small class="orders-note">Only the reference, items, quantities and totals are stored. Customer names, phone numbers and notes are never saved to the server.</small></section></div></div></dialog>
<dialog id="reauth-dialog" class="reauth-dialog"><form id="reauth-form" method="dialog"><div class="dialog-head"><h2>Session expired</h2></div><p class="reauth-note">Your dashboard session timed out. Sign in again and your unsaved changes will be submitted — nothing on screen is lost.</p><label>Admin username<input name="username" required autocomplete="username"></label><label>Admin password<input name="password" type="password" required autocomplete="current-password"></label><?php if(!empty($siteSettings['two_factor_enabled'])):?><label>Authenticator or recovery code<input name="otp" required inputmode="text" maxlength="12" autocomplete="one-time-code"></label><?php endif;?><div id="reauth-error" class="form-error" role="alert"></div><div class="dialog-actions"><button type="button" class="secondary" data-close>Cancel</button><button type="submit">Sign in and continue</button></div></form></dialog>
<link rel="stylesheet" href="../assets/admin-extra.css?v=15"><script nonce="<?=htmlspecialchars(CSP_NONCE)?>">window.ADMIN_CSRF=<?=json_encode(csrf_token())?>;</script><script src="../assets/admin.js?v=15"></script></body></html>
