<?php
declare(strict_types=1);
require_once __DIR__ . '/../inc/bootstrap.php';
$settings=settings(); if(empty($settings['admin_password_hash'])){header('Location: setup.php');exit;} if(is_admin()){header('Location: index.php');exit;}
$error=''; if(empty($_SESSION['admin_login_csrf']))$_SESSION['admin_login_csrf']=bin2hex(random_bytes(24));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals((string)$_SESSION['admin_login_csrf'],(string)($_POST['csrf']??'')))$error='Session expired. Refresh and retry.';
 elseif(!auth_allowed('admin'))$error='Too many incorrect attempts. Please wait 15 minutes.';
 else{$usernameOk=hash_equals(strtolower((string)($settings['admin_username']??'admin')),strtolower(trim((string)($_POST['username']??''))));$passwordOk=password_verify((string)($_POST['password']??''),(string)$settings['admin_password_hash']);$code=(string)($_POST['otp']??'');$secondFactorOk=empty($settings['two_factor_enabled'])||verify_totp((string)$settings['two_factor_secret'],$code);$usedRecovery=false;if(!$secondFactorOk&&$usernameOk&&$passwordOk&&use_recovery_code($settings,$code)){$secondFactorOk=true;$usedRecovery=true;}if($usernameOk&&$passwordOk&&$secondFactorOk){auth_clear_failures('admin');session_regenerate_id(true);$_SESSION['admin_authenticated']=true;$_SESSION['admin_entry_allowed']=true;$_SESSION['customer_authenticated']=true;$_SESSION['admin_last_seen']=time();log_activity('Administrator login',$usedRecovery?'Recovery code used':'Authenticator verified');header('Location: index.php');exit;}auth_record_failure('admin');log_activity('Failed administrator login','Username: '.clean_text($_POST['username']??'',64));usleep(700000);$error='Incorrect administrator credentials'.($settings['two_factor_enabled']?' or verification code.':'.');}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%23ff0000'/%3E%3Crect x='23' y='14' width='18' height='36' rx='4' fill='%23fff'/%3E%3C/svg%3E"><title>DR PHONE Admin</title><link rel="stylesheet" href="../assets/admin.css?v=13"></head><body class="auth-body"><main class="auth-card"><img class="admin-brand-logo" src="../dr-phone-logo.png" alt="Dr. phone"><p class="eyebrow">Catalog management</p><h1>Administrator login</h1><p>Sign in with the single account created during setup.</p><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['admin_login_csrf'])?>"><label>Admin username<input name="username" required autofocus autocomplete="username"></label><label>Admin password<input type="password" name="password" required autocomplete="current-password"></label><?php if($settings['two_factor_enabled']):?><label>Authenticator or recovery code<input name="otp" required inputmode="text" maxlength="12" autocomplete="one-time-code" placeholder="6-digit or recovery code"></label><?php endif;?><?php if($error):?><div class="form-error"><?=htmlspecialchars($error)?></div><?php endif;?><button type="submit">Open dashboard</button></form><a class="text-link" href="../">Return to catalog</a></main></body></html>
